#!/usr/bin/env python

import os
import shutil
import pathlib
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

try:
    import eocfi
except Exception as e:
    print(f'Error importing eocfi: {e}')
    print(f'Please install eocfi:') 
    print('https://eop-cfi.esa.int/index.php/mission-cfi-software/eocfi-software')
    exit(1)

from eocfi.api_xd import xd_read_fhr

from loguru import logger
logger = logger.patch(lambda record: record.update(name=record["file"].name))

from importlib.metadata import version as package_version

# ===========================================================================================================================================================================
# patching configuration according to the redmine issues:
# 
def _init_patching_dates():
    list_patching_dates = []
    patching_element    = {}
    
    '''
    SW#1 Kiruna:
    - 2026-04-24T02:45 / relative orbit#17
    - 2026-07-05T02:49 / relative orbit#17
    - 2026-09-16T18:21 / relative orbit#41
    - 2026-11-27T18:26 / relative orbit#41
    '''

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 17
    patching_element['date_start']      = datetime.strptime('UTC=2026-04-24T02:45:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = 21)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 17
    patching_element['date_start']      = datetime.strptime('UTC=2026-07-05T02:49:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = 21)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 41
    patching_element['date_start']      = datetime.strptime('UTC=2026-09-16T18:21:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = 21)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 41
    patching_element['date_start']      = datetime.strptime('UTC=2026-11-27T18:26:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = 21)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    '''
    SW#1 Inuvik:
    - 2026-02-12T13:02 / relative orbit#38
    - 2026-04-25T13:06 / relative orbit#38
    - 2026-09-15T04:43 / relative orbit#18
    - 2026-11-26T04:47 / relative orbit#18
    '''
    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 38
    patching_element['date_start']      = datetime.strptime('UTC=2026-02-12T13:02:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = 21)
    #logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 38
    patching_element['date_start']      = datetime.strptime('UTC=2026-04-25T13:06:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = 21)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 18
    patching_element['date_start']      = datetime.strptime('UTC=2026-09-15T04:43:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = 21)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 18
    patching_element['date_start']      = datetime.strptime('UTC=2026-11-26T04:47:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = 21)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    '''
    SW#2 Kiruna
    - 2026-03-04T02:40 / relative orbit#17
    - 2026-05-15T02:45 / relative orbit#17
    - 2026-07-26T02:49 / relative orbit#17
    - 2026-12-18T18:26 / relative orbit#41
    - 2027-02-28T18:30 / relative orbit#41
    '''

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 17
    patching_element['date_start']      = datetime.strptime('UTC=2026-03-04T02:40:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = 21)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 17
    patching_element['date_start']      = datetime.strptime('UTC=2026-05-15T02:45:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = 21)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 17
    patching_element['date_start']      = datetime.strptime('UTC=2026-07-26T02:49:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = 21)
    #logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)
    
    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 41
    patching_element['date_start']      = datetime.strptime('UTC=2026-12-18T18:26:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = 21)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 41
    patching_element['date_start']      = datetime.strptime('UTC=2027-02-28T18:30:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = 21)
    #logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    '''
    SW#2 Inuvik:
    - 2026-03-05T13:02 / relative orbit#38
    - 2026-12-17T04:47 / relative orbit#18
    - 2027-01-01T04:47 / relative orbit#18

    '''

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 38
    patching_element['date_start']      = datetime.strptime('UTC=2026-03-05T13:02:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = 21)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 18
    patching_element['date_start']      = datetime.strptime('UTC=2026-12-17T04:47:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = 21)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 18
    patching_element['date_start']      = datetime.strptime('UTC=2027-01-01T04:47:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = 21)
    #logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    '''
    SW#3 Kiruna:
    - 2026-03-25T02:40 / relative orbit#17
    - 2026-06-05T02:45 / relative orbit#17
    '''

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#3'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 17
    patching_element['date_start']      = datetime.strptime('UTC=2026-03-25T02:40:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = 21)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)
    
    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#3'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 17
    patching_element['date_start']      = datetime.strptime('UTC=2026-06-05T02:45:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = 21)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    '''
    SW#3 Inuvik:
    - 2026-03-26T13:02 / relative orbit#38
    '''

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#3'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 38
    patching_element['date_start']      = datetime.strptime('UTC=2026-03-26T13:02:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = 21)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    return list_patching_dates

import click
CONTEXT_SETTINGS = {"help_option_names": ['-h', '--help'], "max_content_width" : 220}

@click.command(context_settings=CONTEXT_SETTINGS, no_args_is_help = True)
@click.option('--file', '-f',                                            help = 'file MPL_PPF_1_ to be patched')
@click.option('--Config', '-C',      is_flag = True, default = False,    help = 'shows patching configuration')
@click.option('--version', '-v',     is_flag = True, default = False,    help = 'It shows the version')
@click.option('--Silent', '-S',      is_flag = True, default = False,    help = 'Avoid logging messages')
@click.option('--Debug', '-D',       is_flag = True, default = False,    help = 'Debug flag for verbose messages')

def patch_ppf_idle_frames(file: str, config: bool, version: bool, silent: bool, debug: bool):

    """
    \b
    Patch the BMPF MPL_PPF_1 for idle frames transmission according to:
    https://redmineng.exprivia.it/issues/6603
    \b
    """

    if version == True:
        print(f"{os.path.basename(__file__)} - {package_version('bcops')}")
        exit(0)

    list_patching_dates = _init_patching_dates()

    if config == True:
        for patching_date in list_patching_dates:
            logger.info(f'Patching config: {patching_date['swath']} {patching_date['date_start']} to {patching_date['date_end']} station {patching_date['station_id']} and relative orbit {patching_date['relative_orbit']}')
        exit(0)

    if pathlib.Path(f'/data/mpf/BMPF/data/outgoing/MPL_PPF___/{file}').exists() == False:
        logger.error(f'file /data/mpf/BMPF/data/outgoing/MPL_PPF___/{file} not found')
        exit(1)

    if pathlib.Path(f'/data/mpf/BMPF/{file}_PATCHED').exists() == True:
        logger.info(f'It seems {file} has been previously patched')
        logger.error(f'file /data/mpf/BMPF/{file}_PATCHED already exists')
        exit(1)

    if pathlib.Path(f'/data/mpf/BMPF/{file}_ORIGINAL').exists() == True:
        logger.info(f'It seems {file} has been previously patched')
        logger.error(f'file /data/mpf/BMPF/{file}_ORIGINAL already exists')
        exit(1)

    logger.info(f'copy file /data/mpf/BMPF/data/outgoing/MPL_PPF___/{file} to /data/mpf/BMPF/{file}_ORIGINAL')
    shutil.copyfile(f'/data/mpf/BMPF/data/outgoing/MPL_PPF___/{file}', f'/data/mpf/BMPF/{file}_ORIGINAL')

    logger.info(f'copy file /data/mpf/BMPF/data/outgoing/MPL_PPF___/{file} to /data/mpf/BMPF/{file}')
    shutil.copyfile(f'/data/mpf/BMPF/data/outgoing/MPL_PPF___/{file}', f'/data/mpf/BMPF/{file}')

    logger.info(f'patching file /data/mpf/BMPF/{file}')

    fhr = xd_read_fhr(f'/data/mpf/BMPF/{file}')
    val_str_start       = fhr['val_start_date']
    val_str_end         = fhr['val_stop_date']
    val_datetime_start  = datetime.strptime(val_str_start, 'UTC=%Y-%m-%dT%H:%M:%S').replace(tzinfo = ZoneInfo('UTC'))
    val_datetime_end    = datetime.strptime(val_str_end, 'UTC=%Y-%m-%dT%H:%M:%S').replace(tzinfo = ZoneInfo('UTC'))
    
    original_file       = file
    
    for patching_date in list_patching_dates:
        if patching_date['date_start'] <= val_datetime_start and patching_date['date_end'] >= val_datetime_start \
            or patching_date['date_start'] <= val_datetime_end and patching_date['date_end'] >= val_datetime_end:
            cmd = f'bcops_bmpf_downlink_idleframes -s {patching_date['date_start'].strftime('%Y-%m-%dT%H:%M:%S')} -e {patching_date['date_end'].strftime('%Y-%m-%dT%H:%M:%S')} --station-id {patching_date["station_id"]} -o {patching_date["relative_orbit"]} -f /data/mpf/BMPF/{file}'
            logger.info(cmd)
            ret = os.system(cmd)
            if ret != 0:
                logger.error(f'Error running command: {cmd}')
                exit(1)
            file = f'{file}_patched'

    logger.info(f'copy file /data/mpf/BMPF/{file} to /data/mpf/BMPF/{original_file}_PATCHED')
    shutil.copyfile(f'/data/mpf/BMPF/{file}', f'/data/mpf/BMPF/{original_file}_PATCHED')

    logger.info(f'replace file to be sent /data/mpf/BMPF/data/outgoing/MPL_PPF___/{original_file} with patched file /data/mpf/BMPF/{original_file}_PATCHED')
    shutil.copyfile(f'/data/mpf/BMPF/{original_file}_PATCHED', f'/data/mpf/BMPF/data/outgoing/MPL_PPF___/{original_file}')

    exit(0)

# ===========================================================================================================================================================================



def version():
    return package_version('bcops')

if __name__ == '__main__':
    patch_ppf_idle_frames()


exit(0)