#!/usr/bin/env python

from loguru import logger
logger = logger.patch(lambda record: record.update(name=record["file"].name))

import click
CONTEXT_SETTINGS = dict(help_option_names=['-h', '--help'])

import os

from fastkml import kml
from lxml import etree


def parse_kml_file_get_datatakes(filename: str):
    
    KML_NS      = "http://www.opengis.net/kml/2.2"
    ns          = {"kml": KML_NS}

    xml_file    = None
    xml_root    = None


    try:
        xml_file = etree.parse(filename)
        xml_root = xml_file.getroot() 
    except:
        logger.error(f'Error parsing {filename}')
        raise(f'Error parsing {filename}')
   
    path                = '//kml:Placemark'
    list_xml_datatake   = xml_root.xpath(path, namespaces=ns)
    list_datatakes      = []
    for pm in list_xml_datatake:
        datatake = {}
        name     = pm.find("{http://www.opengis.net/kml/2.2}name")
        print(name.text)
        extended_data = pm.find("{http://www.opengis.net/kml/2.2}ExtendedData")

        for element_data in extended_data:
            element_name  = element_data.get('name')
            element_value = element_data.find('kml:value', ns).text
            print(element_name)
            print(element_value)
           
            if element_name == 'Datatake Id':
                datatake['datatake_id'] = element_value

            if element_name == 'Mode':
                match element_value:
                    case 'Transponder Calibration Mode':
                        datatake['mode'] = 'S_TRPCAL'
                    case 'Measurement Mode':
                        datatake['mode'] = 'S_MEAS__'
                    case 'Simulation Mode':
                        logger.info(f'Skipping: {element_value}')
                        datatake['mode'] = 'S_SIMUL_'
                        # continue
                    case _:
                        logger.warning(f'Unknown mode: {element_value}')
                        datatake['mode'] = element_value

            if element_name == 'Start Time':
                datatake['start_time'] = element_value

            if element_name == 'Stop Time':
                datatake['stop_time'] = element_value
                
            if element_name == 'Duration':
                datatake['duration'] = element_value

            if element_name == 'Absolute Orbit':
                datatake['absolute_orbit'] = element_value

            if element_name == 'Delta time from ANX':
                datatake['anx_time'] = element_value

            if element_name == 'Phase':
                datatake['phase'] = element_value

            if element_name == 'Sub Phase':
                datatake['sub_phase'] = element_value
                if element_value == 'SRM':
                    datatake['target'] = 'SRM'
                if element_value == 'Imaging':
                    datatake['target'] = 'Primary'

            if element_name == 'Global Cycle':
                datatake['global_coverage'] = element_value

            if element_name == 'Major Cycle':
                datatake['major_cycle'] = element_value

            if element_name == 'Swath Id':
                match element_value:
                    case '1':
                        datatake['swath_id'] = 'Swath#1'
                    case '2':
                        datatake['swath_id'] = 'Swath#2'
                    case '3':
                        datatake['swath_id'] = 'Swath#3'
                    case '4':
                        datatake['swath_id'] = 'SRM'
                    case _:
                        logger.error(f'Unknown swath id: {element_value}')

            if element_name == 'Repeat cycle':
                datatake['repeat_cycle'] = element_value

            if element_name == 'Track':
                datatake['track'] = element_value

            if element_name == 'GSTL Index':
                datatake['gstl_index'] = element_value

            if element_name == 'Warmup':
                datatake['warm_up'] = element_value

        print(datatake)
        list_datatakes.append(datatake)
        exit(0)

    exit(0)


    print('PEDO0')
    k = kml.KML.parse(filename)
    print('PEDO1')
    exit(0)
    feature_datatakes = k.features[0].features[0].features
    logger.info(f'Document - {k.features[0].name}')
    print('PEDO')
    exit(0)
    list_datatakes = []

    for feature in feature_datatakes:
        print('PEDO')
        exit(0)
        print(feature)
        exit(0)
        datatake = {}
        # logger.info(f'Feature name: {feature.name}')
   
        features = list(feature.features)
        
        for f in features:
        # this is the <name>2025-11-24T00:17:41</name>
        # logger.info(f'Feature name: {f.name}')
        # logger.info(f'Feature description: {f.description}')
        # logger.info(f'Feature geometry: {f.geometry.coords}')
        # logger.info(f'Feature styleUrl: {f.style_url}')
        # logger.info(f'Feature extendedData: {f.extended_data}')
        
            initial_format_coordinates = str( f.geometry.coords )
            initial_format_coordinates = initial_format_coordinates.replace(", ", ",")
            initial_format_coordinates = initial_format_coordinates.replace("),", " ")
            initial_format_coordinates = initial_format_coordinates.replace("(", "")
            initial_format_coordinates = initial_format_coordinates.replace(")", "")
            datatake['coordinates']    = initial_format_coordinates
            # print(initial_format_coordinates)

            for element in f.extended_data.elements:
                if element.name == 'Datatake Id':
                    datatake['datatake_id'] = element.value

                if element.name == 'Mode':
                    match element.value:
                        case 'Transponder Calibration Mode':
                            datatake['mode'] = 'S_TRPCAL'
                        case 'Measurement Mode':
                            datatake['mode'] = 'S_MEAS__'
                        case 'Simulation Mode':
                            logger.info(f'Skipping: {element.value}')
                            datatake['mode'] = 'S_SIMUL_'
                            # continue
                        case _:
                            logger.warning(f'Unknown mode: {element.value}')
                            datatake['mode'] = element.value

                if element.name == 'Start Time':
                    datatake['start_time'] = element.value

                if element.name == 'Stop Time':
                    datatake['stop_time'] = element.value
                   
                if element.name == 'Duration':
                    datatake['duration'] = element.value

                if element.name == 'Absolute Orbit':
                    datatake['absolute_orbit'] = element.value

                if element.name == 'Delta time from ANX':
                    datatake['anx_time'] = element.value

                if element.name == 'Phase':
                    datatake['phase'] = element.value

                if element.name == 'Sub Phase':
                    datatake['sub_phase'] = element.value
                    if element.value == 'SRM':
                        datatake['target'] = 'SRM'
                    if element.value == 'Imaging':
                        datatake['target'] = 'Primary'

                if element.name == 'Global Cycle':
                    datatake['global_coverage'] = element.value

                if element.name == 'Major Cycle':
                    datatake['major_cycle'] = element.value

                if element.name == 'Swath Id':
                    match element.value:
                        case '1':
                            datatake['swath_id'] = 'Swath#1'
                        case '2':
                            datatake['swath_id'] = 'Swath#2'
                        case '3':
                            datatake['swath_id'] = 'Swath#3'
                        case '4':
                            datatake['swath_id'] = 'SRM'
                        case _:
                            logger.error(f'Unknown swath id: {element.value}')

                if element.name == 'Repeat cycle':
                    datatake['repeat_cycle'] = element.value

                if element.name == 'Track':
                    datatake['track'] = element.value

                if element.name == 'GSTL Index':
                    datatake['gstl_index'] = element.value

                if element.name == 'Warmup':
                    datatake['warm_up'] = element.value

            list_datatakes.append(datatake)

            print(datatake)
            exit(0)
            
    return list_datatakes    


def create_kml_file_datatakes(filename: str, document_name: str, list_datatakes: list):
    current_phase           = list_datatakes[0]['phase']
    current_global_coverage = list_datatakes[0]['global_coverage']
    current_major_cycle     = list_datatakes[0]['major_cycle']
    current_swath_id        = list_datatakes[0]['swath_id']
    
    logger.info(f'creating KML file - {filename}')
    ns   = '{http://www.opengis.net/kml/2.2}'
    root = etree.Element(f'{ns}kml')
    doc  = etree.SubElement(root, 'Document')
    name = etree.SubElement(doc, 'name')
    name.text = document_name

    first_folder_phase = etree.SubElement(doc, 'Folder')
    name = etree.SubElement(first_folder_phase, 'name')
    name.text = current_phase
    desc = etree.SubElement(first_folder_phase, 'description')
    desc.text = 'Mission Phase'

    first_folder_global_coverage = etree.SubElement(first_folder_phase, 'Folder')
    name = etree.SubElement(first_folder_global_coverage, 'name')
    name.text = current_global_coverage
    desc = etree.SubElement(first_folder_global_coverage, 'description')
    desc.text = 'Global Coverage'

    first_folder_major_cycle = etree.SubElement(first_folder_global_coverage, 'Folder')
    name = etree.SubElement(first_folder_major_cycle, 'name')
    name.text = current_major_cycle
    desc = etree.SubElement(first_folder_major_cycle, 'description')
    desc.text = 'Major Cycle'

    first_folder_swath_id = etree.SubElement(first_folder_major_cycle, 'Folder')
    name = etree.SubElement(first_folder_swath_id, 'name')
    name.text = current_swath_id
    desc = etree.SubElement(first_folder_swath_id, 'description')
    desc.text = 'Swath Cycle'

    folder_global_coverage = first_folder_global_coverage
    folder_major_cycle     = first_folder_major_cycle
    folder_swath_id        = first_folder_swath_id

    for datatake in list_datatakes:

        print(f"Processing datatake")
        print(datatake)
        exit(0)

        # change of mission phase
        if datatake['phase'] != current_phase:
            current_phase = datatake['phase'] 
            logger.info('change of mission phase')
            logger.warning('change of mission phase not implemented')
            pass

        # change of global coverage
        if datatake['global_coverage'] != current_global_coverage:
            current_global_coverage = datatake['global_coverage'] 
            logger.info('change of global coverage')
            logger.warning('change of global coverage not implemented')
            pass

        # change of major cycle
        if datatake['major_cycle'] != current_major_cycle:
            logger.info('change of major cycle')
            current_major_cycle = datatake['major_cycle'] 
            folder_major_cycle  = etree.SubElement(folder_global_coverage, 'Folder')
            name = etree.SubElement(folder_major_cycle, 'name')
            name.text = current_major_cycle
            desc = etree.SubElement(folder_major_cycle, 'description')
            desc.text = 'Major Cycle'

        # change of swath id
        if datatake['swath_id'] != current_swath_id:
            logger.info('change of swath id')
            current_swath_id = datatake['swath_id']
            folder_swath_id = etree.SubElement(folder_major_cycle, 'Folder')
            name = etree.SubElement(folder_swath_id, 'name')
            name.text = current_swath_id
            desc = etree.SubElement(folder_swath_id, 'description')
            desc.text = 'Swath Cycle'

        folder_datatake = etree.SubElement(folder_swath_id, 'Folder')
        name = etree.SubElement(folder_datatake, 'name')
        name.text = f"{datatake['start_time']} - {datatake['mode']}"
        desc = etree.SubElement(folder_datatake, 'description')
        desc.text = 'DataTake'
        
        placemark = etree.SubElement(folder_datatake, 'Placemark')
        name = etree.SubElement(placemark, 'name')
        name.text = f"{datatake['start_time']} - {datatake['mode']} - GSTL#{datatake['gstl_index']}"

        timespan = etree.SubElement(placemark, 'TimeSpan')
        begin    = etree.SubElement(timespan, 'begin')
        begin.text = datatake['start_time']
        end      = etree.SubElement(timespan, 'end')
        end.text = datatake['stop_time']

        extended = etree.SubElement(placemark, 'ExtendedData')

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Satellite Id')
        value = etree.SubElement(data, 'value')
        value.text = 'BIOMASS'

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Datatake Id')
        value = etree.SubElement(data, 'value')
        value.text = datatake['datatake_id']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Mode')
        value = etree.SubElement(data, 'value')
        value.text = datatake['mode']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'GSTL')
        value = etree.SubElement(data, 'value')
        value.text = datatake['gstl_index']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Swath Id')
        value = etree.SubElement(data, 'value')
        value.text = datatake['swath_id']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Start Time')
        value = etree.SubElement(data, 'value')
        value.text = datatake['start_time']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Stop Time')
        value = etree.SubElement(data, 'value')
        value.text = datatake['stop_time']
      
        data = etree.SubElement(extended, "Data")
        data.set('name', 'Duration')
        value = etree.SubElement(data, 'value')
        value.text = datatake['duration']
      
        data = etree.SubElement(extended, "Data")
        data.set('name', 'Absolute Orbit')
        value = etree.SubElement(data, 'value')
        value.text = datatake['absolute_orbit']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Delta time from ANX')
        value = etree.SubElement(data, 'value')
        value.text = datatake['anx_time']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Phase')
        value = etree.SubElement(data, 'value')
        value.text = datatake['phase']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Global Coverage')
        value = etree.SubElement(data, 'value')
        value.text = datatake['global_coverage']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Major Cycle')
        value = etree.SubElement(data, 'value')
        value.text = datatake['major_cycle']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Repeat Cycle')
        value = etree.SubElement(data, 'value')
        value.text = datatake['repeat_cycle']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Track')
        value = etree.SubElement(data, 'value')
        value.text = datatake['track']

        linear_ring = etree.SubElement(placemark, 'LinearRing')
        tesselate   = etree.SubElement(linear_ring, 'tessellate')
        tesselate.text = 'true'
        altitude    = etree.SubElement(linear_ring, 'altitudeMode')
        altitude.text = 'clampToGround'
        coordinates = etree.SubElement(linear_ring, 'coordinates')
        coordinates.text = datatake['coordinates']

    tree = etree.ElementTree(root)
    tree.write(filename, encoding='utf-8', xml_declaration=True, pretty_print=True)

import click
CONTEXT_SETTINGS = dict(help_option_names=['-h', '--help'])

@click.command(context_settings=CONTEXT_SETTINGS, no_args_is_help = True)
@click.option('--file-input', '-i',     help = 'full path file with the input KML')
@click.option('--file-output', '-o',    help = 'full path file with the output KML')
@click.option('--version', '-v',     is_flag = True, default = False,    help = 'It shows the version')
@click.option('--License', '-L',     is_flag = True, default = False,    help = 'Print License')
@click.option('--Silent', '-S',      is_flag = True, default = False,    help = 'Silent flag to avoid log messages and obtain the JSON result')
@click.option('--Debug', '-D',       is_flag = True, default = False,    help = 'Debug flag for verbose messages')


def reshuffle_datatakes_kml(file_input, file_output, version, license, silent, debug):
    """
    \b
    Reformat KML Biomass data-takes to the mission hierarchy:
    > Phase: TOM|INT
    > Global Coverage
    > Major Cycle
    > Swath Cycle
    
    \b
    """
    if version == True:
        print(f"{os.path.basename(__file__)} - KK version")
        exit(0)

    if license == True:
        print(f"{os.path.basename(__file__)} - TBW license")
        # print_license()
        exit(0)

    if silent == True and debug == True:
        print(f"Error: --Silent and --Debug flags are mutually exclusive")
        exit(66)

    if file_input == None:
        print(f"Error: --file-input is mandatory")
        exit(66)

    # check if exists the file-input

    if file_output == None:
        print(f"Error: --file-output is mandatory")
        exit(66)

    logger.info('starting bioswath')
    list_datatakes = parse_kml_file_get_datatakes(filename = file_input)
    create_kml_file_datatakes(filename = file_output, document_name = 'my document', list_datatakes=list_datatakes)

if __name__ == '__main__':
    reshuffle_datatakes_kml()
