#!/usr/bin/env python
import os
import click
from fileinput import filename
from loguru import logger
from importlib.metadata import version as package_version
from lxml import etree

logger = logger.patch(lambda record: record.update(name=record["file"].name))

CONTEXT_SETTINGS = dict(help_option_names=['-h', '--help'])

KML_STYLESHEET   = {'Swath_1-S_MEAS__'  :'FFC8DC77', 
                    'Swath_2-S_MEAS__'  :'FF0B9267', 
                    'Swath_3-S_MEAS__'  :'FF0D6B31', 
                    'SRM-S_MEAS__'      :'FFF58114'}

def parse_kml_file_get_datatakes(filename: str, debug: bool = False) -> list:
    KML_NS      = "http://www.opengis.net/kml/2.2"
    ns          = {"kml": KML_NS}
    xml_file    = None
    xml_root    = None
    try:
        if debug == True:
            logger.debug('start parsing KML file to get datatakes')
        xml_file = etree.parse(filename)
        xml_root = xml_file.getroot()
        if debug == True:
            logger.debug('end parsing KML file to get datatakes')
    except:
        logger.error(f'Error parsing {filename}')
        raise(f'Error parsing {filename}')
   
    path                = '//kml:Placemark'
    list_xml_datatake   = xml_root.xpath(path, namespaces=ns)
    list_datatakes      = []

    if debug == True:
        logger.debug( f"Number of datatakes found: {len(list_xml_datatake)}" )
    
    for pm in list_xml_datatake:
        datatake                = {}
        name                    = pm.find('kml:name', ns)
        extended_data           = pm.findall(".//kml:ExtendedData", ns)[0]
        linear_ring             = pm.findall('.//kml:LinearRing', ns)[0]
        linear_ring_coordinates = pm.findall('.//kml:coordinates', ns)[0]
        format_coordinates      = etree.tostring(linear_ring_coordinates, pretty_print = True).decode('utf-8').strip().replace(' xmlns=\"http://www.opengis.net/kml/2.2\"', '')
        datatake['coordinates'] = format_coordinates
        datatake['coordinates'] = linear_ring_coordinates.text
        
        for element_data in extended_data:
            element_name  = element_data.get('name')
            element_value = element_data.find('kml:value', ns).text
            
            if element_name == 'Datatake Id':
                datatake['datatake_id'] = element_value

            if element_name == 'Mode':
                match element_value:
                    case 'Transponder Calibration Mode':
                        datatake['mode'] = 'S_TRPCAL'
                    case 'Measurement Mode':
                        datatake['mode'] = 'S_MEAS__'
                    case 'Simulation Mode':
                        logger.info(f'Skipping: {element_value}')
                        datatake['mode'] = 'S_SIMUL_'
                        # continue
                    case _:
                        logger.warning(f'Unknown mode: {element_value}')
                        datatake['mode'] = element_value

            if element_name == 'Start Time':
                datatake['start_time'] = element_value

            if element_name == 'Stop Time':
                datatake['stop_time'] = element_value
                
            if element_name == 'Duration':
                datatake['duration'] = element_value

            if element_name == 'Absolute Orbit':
                datatake['absolute_orbit'] = element_value

            if element_name == 'Delta time from ANX':
                datatake['anx_time'] = element_value

            if element_name == 'Phase':
                datatake['phase'] = element_value

            if element_name == 'Sub Phase':
                datatake['sub_phase'] = element_value
                if element_value == 'SRM':
                    datatake['target'] = 'SRM'
                if element_value == 'Imaging':
                    datatake['target'] = 'Primary'

            if element_name == 'Global Cycle':
                datatake['global_coverage'] = element_value

            if element_name == 'Major Cycle':
                datatake['major_cycle'] = element_value

            if element_name == 'Swath Id':
                match element_value:
                    case '1':
                        datatake['swath_id'] = 'Swath#1'
                    case '2':
                        datatake['swath_id'] = 'Swath#2'
                    case '3':
                        datatake['swath_id'] = 'Swath#3'
                    case '4':
                        datatake['swath_id'] = 'SRM'
                    case _:
                        logger.error(f'Unknown swath id: {element_value}')

            if element_name == 'Repeat cycle':
                datatake['repeat_cycle'] = element_value

            if element_name == 'Track':
                datatake['track'] = element_value

            if element_name == 'GSTL Index':
                datatake['gstl_index'] = element_value

            if element_name == 'Warmup':
                datatake['warm_up'] = element_value

        if debug == True:
            logger.debug( "Placemark: " + name.text + " datatake_id: " + datatake['datatake_id'] )
        
        list_datatakes.append(datatake)
    
    return list_datatakes


def create_kml_file_datatakes(filename: str, document_name: str, list_datatakes: list):
    logger.info(f'creating KML file - {filename}')

    current_phase           = list_datatakes[0]['phase']
    current_global_coverage = list_datatakes[0]['global_coverage']
    current_major_cycle     = list_datatakes[0]['major_cycle']
    current_swath_id        = list_datatakes[0]['swath_id']

    logger.info(f'Phase - {current_phase}')
    logger.info(f'Global Coverage - {current_global_coverage}')
    logger.info(f'Major Cycle     - {current_major_cycle}')
    logger.info(f'Swath ID        - {current_swath_id}')

    ns   = 'http://www.opengis.net/kml/2.2'
    etree.register_namespace('kml', ns)
    root = etree.Element('kml', namespace = ns)
    doc  = etree.SubElement(root, 'Document')
    name = etree.SubElement(doc, 'name')
    name.text = document_name

    for stylesheet in KML_STYLESHEET:
        style = etree.SubElement(doc, 'Style')
        style.set('id', stylesheet)
        linestyle = etree.SubElement(style, 'LineStyle')
        color     = etree.SubElement(linestyle, 'color')
        color.text= KML_STYLESHEET[stylesheet]
        width     = etree.SubElement(linestyle, 'width')
        width.text= '2'

    first_folder_phase = etree.SubElement(doc, 'Folder')
    name = etree.SubElement(first_folder_phase, 'name')
    name.text = current_phase
    desc = etree.SubElement(first_folder_phase, 'description')
    desc.text = 'Mission Phase'

    first_folder_global_coverage = etree.SubElement(first_folder_phase, 'Folder')
    name = etree.SubElement(first_folder_global_coverage, 'name')
    name.text = current_global_coverage
    desc = etree.SubElement(first_folder_global_coverage, 'description')
    desc.text = 'Global Coverage'

    first_folder_major_cycle = etree.SubElement(first_folder_global_coverage, 'Folder')
    name = etree.SubElement(first_folder_major_cycle, 'name')
    name.text = current_major_cycle
    desc = etree.SubElement(first_folder_major_cycle, 'description')
    desc.text = 'Major Cycle'

    first_folder_swath_id = etree.SubElement(first_folder_major_cycle, 'Folder')
    name = etree.SubElement(first_folder_swath_id, 'name')
    name.text = current_swath_id
    desc = etree.SubElement(first_folder_swath_id, 'description')
    desc.text = 'Swath Cycle'

    folder_global_coverage = first_folder_global_coverage
    folder_major_cycle     = first_folder_major_cycle
    folder_swath_id        = first_folder_swath_id

    for datatake in list_datatakes:
        # change of mission phase
        if datatake['phase'] != current_phase:
            current_phase = datatake['phase'] 
            logger.info('change of mission phase')
            logger.warning('change of mission phase not implemented')
            pass

        # change of global coverage
        if datatake['global_coverage'] != current_global_coverage:
            current_global_coverage = datatake['global_coverage'] 
            logger.info('change of global coverage')
            logger.warning('change of global coverage not implemented')
            pass

        # change of major cycle
        if datatake['major_cycle'] != current_major_cycle:
            # logger.info('change of major cycle')
            current_major_cycle = datatake['major_cycle']
            logger.info(f'Major Cycle     - {current_major_cycle}')
            folder_major_cycle  = etree.SubElement(folder_global_coverage, 'Folder')
            name = etree.SubElement(folder_major_cycle, 'name')
            name.text = current_major_cycle
            desc = etree.SubElement(folder_major_cycle, 'description')
            desc.text = 'Major Cycle'

        # change of swath id
        if datatake['swath_id'] != current_swath_id:
            # logger.info('change of swath id')
            current_swath_id = datatake['swath_id']
            logger.info(f'Swath ID        - {current_swath_id}')
            folder_swath_id = etree.SubElement(folder_major_cycle, 'Folder')
            name = etree.SubElement(folder_swath_id, 'name')
            name.text = current_swath_id
            desc = etree.SubElement(folder_swath_id, 'description')
            desc.text = 'Swath Cycle'

        folder_datatake = etree.SubElement(folder_swath_id, 'Folder')
        name = etree.SubElement(folder_datatake, 'name')
        name.text = f"{datatake['start_time']} - {datatake['mode']}"
        desc = etree.SubElement(folder_datatake, 'description')
        desc.text = 'DataTake'
        
        placemark = etree.SubElement(folder_datatake, 'Placemark')
        name = etree.SubElement(placemark, 'name')
        name.text = f"{datatake['start_time']} - {datatake['mode']} - GSTL#{datatake['gstl_index']}"

        timespan = etree.SubElement(placemark, 'TimeSpan')
        begin    = etree.SubElement(timespan, 'begin')
        begin.text = datatake['start_time']
        end      = etree.SubElement(timespan, 'end')
        end.text = datatake['stop_time']

        styleurl = etree.SubElement(placemark, 'styleUrl')
        match datatake['swath_id']:
            case 'Swath#1':
                styleurl.text = '#Swath_1-S_MEAS__'
            case 'Swath#2':
                styleurl.text = '#Swath_2-S_MEAS__'
            case 'Swath#3':
                styleurl.text = '#Swath_3-S_MEAS__'
            case 'SRM':
                styleurl.text = '#SRM-S_MEAS__'
            case _:
                logger.error(f'Unknown swath id: {datatake["swath_id"]}')

        extended = etree.SubElement(placemark, 'ExtendedData')

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Satellite Id')
        value = etree.SubElement(data, 'value')
        value.text = 'BIOMASS'

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Datatake Id')
        value = etree.SubElement(data, 'value')
        value.text = datatake['datatake_id']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Mode')
        value = etree.SubElement(data, 'value')
        value.text = datatake['mode']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'GSTL')
        value = etree.SubElement(data, 'value')
        value.text = datatake['gstl_index']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Swath Id')
        value = etree.SubElement(data, 'value')
        value.text = datatake['swath_id']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Start Time')
        value = etree.SubElement(data, 'value')
        value.text = datatake['start_time']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Stop Time')
        value = etree.SubElement(data, 'value')
        value.text = datatake['stop_time']
      
        data = etree.SubElement(extended, "Data")
        data.set('name', 'Duration')
        value = etree.SubElement(data, 'value')
        value.text = datatake['duration']
      
        data = etree.SubElement(extended, "Data")
        data.set('name', 'Absolute Orbit')
        value = etree.SubElement(data, 'value')
        value.text = datatake['absolute_orbit']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Delta time from ANX')
        value = etree.SubElement(data, 'value')
        value.text = datatake['anx_time']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Phase')
        value = etree.SubElement(data, 'value')
        value.text = datatake['phase']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Global Coverage')
        value = etree.SubElement(data, 'value')
        value.text = datatake['global_coverage']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Major Cycle')
        value = etree.SubElement(data, 'value')
        value.text = datatake['major_cycle']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Repeat Cycle')
        value = etree.SubElement(data, 'value')
        value.text = datatake['repeat_cycle']

        data = etree.SubElement(extended, "Data")
        data.set('name', 'Track')
        value = etree.SubElement(data, 'value')
        value.text = datatake['track']

        linear_ring     = etree.SubElement(placemark, 'LinearRing')
        tesselate       = etree.SubElement(linear_ring, 'tessellate')
        tesselate.text  = 'true'
        altitude        = etree.SubElement(linear_ring, 'altitudeMode')
        altitude.text   = 'clampToGround'
        coordinates     = etree.SubElement(linear_ring, 'coordinates')
        coordinates.text = datatake['coordinates']

    tree = etree.ElementTree(root)
    tree.write(filename, encoding = 'utf-8', xml_declaration = True, pretty_print = True)

import click
CONTEXT_SETTINGS = dict(help_option_names=['-h', '--help'])

@click.command(context_settings = CONTEXT_SETTINGS, no_args_is_help = True)
@click.option('--file-input', '-i',     help = 'full path file with the input KML')
@click.option('--file-output', '-o',    help = 'full path file with the output KML')
@click.option('--version', '-v',     is_flag = True, default = False,    help = 'It shows the version')
@click.option('--License', '-L',     is_flag = True, default = False,    help = 'Print License')
@click.option('--Silent', '-S',      is_flag = True, default = False,    help = 'Silent flag to avoid log messages and obtain the JSON result')
@click.option('--Debug', '-D',       is_flag = True, default = False,    help = 'Debug flag for verbose messages')


def reshuffle_datatakes_kml(file_input, file_output, version, license, silent, debug):
    """
    \b
    Re-shuffle the KML Biomass data-takes to the mission hierarchy:
    > Phase: TOM|INT
    > Global Coverage
    > Major Cycle
    > Swath Cycle
    
    \b
    """
    if version == True:
        print(f"{os.path.basename(__file__)} - KK version")
        exit(0)

    if license == True:
        print(f"{os.path.basename(__file__)} - TBW license")
        # print_license()
        exit(0)

    if silent == True and debug == True:
        print(f"Error: --Silent and --Debug flags are mutually exclusive")
        exit(66)

    if file_input == None:
        print(f"Error: --file-input is mandatory")
        exit(66)

    # check if exists the file-input

    if file_output == None:
        print(f"Error: --file-output is mandatory")
        exit(66)

    logger.info('starting bcops_bmpf_kml_arrange')
    list_datatakes = parse_kml_file_get_datatakes(filename = file_input, debug = debug)
    create_kml_file_datatakes(filename = file_output, document_name = 'Biomass Core Operations Service', list_datatakes=list_datatakes)

def version():
    return package_version('bcops')

if __name__ == '__main__':
    reshuffle_datatakes_kml()
