#!/usr/bin/env python

import os
import shutil
import pathlib
import importlib
import traceback
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

try:
    import eocfi
except Exception as e:
    print(f'Error importing eocfi: {e}')
    print(f'Please install eocfi:') 
    print('https://eop-cfi.esa.int/index.php/mission-cfi-software/eocfi-software')
    exit(1)

from eocfi.constants import XL_ASCII_CCSDSA_COMPACT
from eocfi.constants import XL_PROC
from eocfi.constants import XL_TIME_UTC

from eocfi.api_xd import xd_read_fhr
from eocfi.api_xl import xl_time_ref_init_file
from eocfi.api_xl import xl_time_ascii_to_processing
from eocfi.api_xo import xo_orbit_init_file
from eocfi.api_xo import xo_time_to_orbit
from eocfi.api_xo import xo_orbit_rel_from_abs
from eocfi.api_xo import xo_orbit_close
from eocfi.api_xo import xo_verbose

from loguru import logger
logger = logger.patch(lambda record: record.update(name=record["file"].name))

from importlib.metadata import version as package_version

# 
# (20/60)/24
# .01388888888888888888
#  20 minutes
REPEAT_CYCLE_DAYS_PLUS_MARGINS = 21.01389

# ===========================================================================================================================================================================
# patching configuration according to the redmine issues:
# 
def _init_patching_dates():
    list_patching_dates = []
    patching_element    = {}
    
    '''
    SW#1 Kiruna:
    - 2026-04-24T02:45 / relative orbit#17
    - 2026-07-05T02:49 / relative orbit#17
    - 2026-07-06T18:16 / relative orbit#41
    - 2026-04-25T18:12 / relative orbit#41
    - 2026-09-15T02:54 / relative orbit#17
    - 2026-09-16T18:21 / relative orbit#41
    - 2026-11-26T02:58 / relative orbit#17
    - 2026-11-27T18:26 / relative orbit#41
    '''

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 17
    patching_element['date_start']      = datetime.strptime('UTC=2026-04-24T02:45:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 41
    patching_element['date_start']      = datetime.strptime('UTC=2026-04-25T18:12:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 17
    patching_element['date_start']      = datetime.strptime('UTC=2026-07-05T02:49:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 41
    patching_element['date_start']      = datetime.strptime('UTC=2026-07-06T18:16:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 17
    patching_element['date_start']      = datetime.strptime('UTC=2026-09-15T02:54:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 41
    patching_element['date_start']      = datetime.strptime('UTC=2026-09-16T18:21:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 17
    patching_element['date_start']      = datetime.strptime('UTC=2026-11-26T02:58:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 41
    patching_element['date_start']      = datetime.strptime('UTC=2026-11-27T18:26:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    '''
    SW#1 Inuvik:
    - 2026-02-12T13:02 / relative orbit#38
    - 2026-04-24T04:33 / relative orbit#18
    - 2026-04-25T13:06 / relative orbit#38
    - 2026-07-05T04:38 / relative orbit#18
    - 2026-07-06T13:11 / relative orbit#38
    - 2026-09-15T04:43 / relative orbit#18
    - 2026-09-16T13:15 / relative orbit#38
    - 2026-11-26T04:47 / relative orbit#18
    '''
    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 38
    patching_element['date_start']      = datetime.strptime('UTC=2026-02-12T13:02:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    #logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 18
    patching_element['date_start']      = datetime.strptime('UTC=2026-04-24T04:33:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 38
    patching_element['date_start']      = datetime.strptime('UTC=2026-04-25T13:06:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 18
    patching_element['date_start']      = datetime.strptime('UTC=2026-07-05T04:38:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    #logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 38
    patching_element['date_start']      = datetime.strptime('UTC=2026-07-06T13:11:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    #logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 18
    patching_element['date_start']      = datetime.strptime('UTC=2026-09-15T04:43:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 38
    patching_element['date_start']      = datetime.strptime('UTC=2026-09-16T13:15:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#1'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 18
    patching_element['date_start']      = datetime.strptime('UTC=2026-11-26T04:47:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    '''
    SW#2 Kiruna
    - 2026-03-04T02:40 / relative orbit#17
    - 2026-05-15T02:45 / relative orbit#17
    - 2026-07-26T02:49 / relative orbit#17
    - 2026-07-27T18:16 / relative orbit#41
    - 2026-10-06T02:54 / relative orbit#17
    - 2026-10-07T18:21 / relative orbit#41
    - 2026-12-18T18:26 / relative orbit#41
    - 2027-02-28T18:30 / relative orbit#41
    '''

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 17
    patching_element['date_start']      = datetime.strptime('UTC=2026-03-04T02:40:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 17
    patching_element['date_start']      = datetime.strptime('UTC=2026-05-15T02:45:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 17
    patching_element['date_start']      = datetime.strptime('UTC=2026-07-26T02:49:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    #logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)
    
    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 41
    patching_element['date_start']      = datetime.strptime('UTC=2026-07-27T18:16:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    #logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 17
    patching_element['date_start']      = datetime.strptime('UTC=2026-10-06T02:54:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    #logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 41
    patching_element['date_start']      = datetime.strptime('UTC=2026-10-07T18:21:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    #logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 41
    patching_element['date_start']      = datetime.strptime('UTC=2026-12-18T18:26:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 41
    patching_element['date_start']      = datetime.strptime('UTC=2027-02-28T18:30:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    #logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    '''
    SW#2 Inuvik:
    - 2026-03-05T13:02 / relative orbit#38
    - 2026-05-16T13:07 / relative orbit#38
    - 2026-07-26T04:38 / relative orbit#18
    - 2026-07-27T13:11 / relative orbit#38
    - 2026-10-06T04:43 / relative orbit#18
    - 2026-12-17T04:47 / relative orbit#18
    - 2027-01-01T04:47 / relative orbit#18

    '''

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 38
    patching_element['date_start']      = datetime.strptime('UTC=2026-03-05T13:02:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 38
    patching_element['date_start']      = datetime.strptime('UTC=2026-05-16T13:07:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 18
    patching_element['date_start']      = datetime.strptime('UTC=2026-07-26T04:38:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 38
    patching_element['date_start']      = datetime.strptime('UTC=2026-07-27T13:11:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 18
    patching_element['date_start']      = datetime.strptime('UTC=2026-10-06T04:43:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 18
    patching_element['date_start']      = datetime.strptime('UTC=2026-12-17T04:47:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#2'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 18
    patching_element['date_start']      = datetime.strptime('UTC=2027-01-01T04:47:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    #logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    '''
    SW#3 Kiruna:
    - 2026-03-25T02:40 / relative orbit#17
    - 2026-06-05T02:45 / relative orbit#17
    - 2026-08-16T02:50 / relative orbit#17
    - 2026-10-27T02:54 / relative orbit#17
    - 2026-10-28T18:21 / relative orbit#41
    - 2027-01-08T18:26 / relative orbit#41
    '''

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#3'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 17
    patching_element['date_start']      = datetime.strptime('UTC=2026-03-25T02:40:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)
    
    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#3'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 17
    patching_element['date_start']      = datetime.strptime('UTC=2026-06-05T02:45:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#3'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 17
    patching_element['date_start']      = datetime.strptime('UTC=2026-08-16T02:50:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#3'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 17
    patching_element['date_start']      = datetime.strptime('UTC=2026-10-27T02:54:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#3'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 41
    patching_element['date_start']      = datetime.strptime('UTC=2026-10-28T18:21:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#3'
    patching_element['station_id']      = 'KSE_____'
    patching_element['relative_orbit']  = 41
    patching_element['date_start']      = datetime.strptime('UTC=2027-01-08T18:26:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    '''
    SW#3 Inuvik:
    - 2026-03-26T13:02 / relative orbit#38
    - 2026-06-06T13:07 / relative orbit#38
    - 2026-08-16T04:38 / relative orbit#18
    - 2026-10-27T04:43 / relative orbit#18
    - 2027-01-07T04:48 / relative orbit#18
    '''

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#3'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 38
    patching_element['date_start']      = datetime.strptime('UTC=2026-03-26T13:02:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#3'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 38
    patching_element['date_start']      = datetime.strptime('UTC=2026-06-06T13:07:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#3'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 18
    patching_element['date_start']      = datetime.strptime('UTC=2026-08-16T04:38:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#3'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 18
    patching_element['date_start']      = datetime.strptime('UTC=2026-10-27T04:43:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)

    patching_element = patching_element.copy()
    patching_element['swath']           = 'SW#3'
    patching_element['station_id']      = 'IVK_____'
    patching_element['relative_orbit']  = 18
    patching_element['date_start']      = datetime.strptime('UTC=2027-01-07T04:48:00+0000', 'UTC=%Y-%m-%dT%H:%M:%S%z')
    patching_element['date_end']        = patching_element['date_start'] + timedelta(days = REPEAT_CYCLE_DAYS_PLUS_MARGINS)
    # logger.info(f'Patching config: {patching_element['date_start']} to {patching_element['date_end']} station {patching_element["station_id"]} and relative orbit {patching_element["relative_orbit"]}')
    list_patching_dates.append(patching_element)
    return list_patching_dates


# ===========================================================================================================================================================================
# initialise the EOCFI:
# 
def _init_eocfi(debug: bool = False):
    dist                = importlib.metadata.distribution('eocfi')
    root_dist_info      = dist._path
    dist_info_dir       = pathlib.Path(dist._path).parent
    package_root_dir    = f'{dist_info_dir}/bcops'

    file_orbsct       = f'{dist_info_dir}/bcops/data/BIO_COPS_MPL_ORBSCT'
    
    if debug == True:
        logger.info(f'xl_time_ref_init_file {file_orbsct}')
    try:
        xl_time_ref_init_file(file_orbsct, debug)
    except Exception as error:
        logger.error(f"Failed to init the time reference xl_time_ref_init_file with file {file_orbsct}")
        logger.error(error)
        exit(99)

    if debug == True:
        logger.info(f'xo_verbose')
        xo_verbose(debug)

    if debug == True:
        logger.info(f'xo_orbit_init_file {file_orbsct}')
    try:
        xo_orbit_init_file(file_orbsct, debug)
    except Exception as error:
        logger.error(f"Failed to init the orbit reference xo_orbit_init_file with file {file_orbsct}")
        logger.error(error)
        if debug == True:
            print(traceback.format_exc())
        exit(99)
    return


# =================================================================================================
# get the absolute orbits to be patched in the configured time windows:
def _get_eocfi_mjd2000_from_datetime(datetime_input: datetime, debug: bool = False):
    ascii_id_in         = XL_ASCII_CCSDSA_COMPACT
    time_ref_in         = XL_TIME_UTC
    ascii_in            = datetime_input.strftime('%Y%m%dT%H%M%S')
    proc_id_out         = XL_PROC
    time_ref_out        = XL_TIME_UTC
    mjd2000             = xl_time_ascii_to_processing(
                                    ascii_id_in,
                                    time_ref_in,
                                    ascii_in,
                                    proc_id_out,
                                    time_ref_out,
                                    debug)
    return mjd2000


# =================================================================================================
# get the absolute orbits to be patched in the configured time windows:
def _get_eocfi_orbit_from_mjd2000(mjd2000_time: float, debug: bool = False):
    time_ref    = XL_TIME_UTC
    abs_orbit   = xo_time_to_orbit(time_ref, mjd2000_time, debug)
    return abs_orbit


# =================================================================================================
# get the absolute orbits to be patched in the configured time windows:
# 
def _get_patching_abs_orbit(list_patching_dates: list, debug: bool = False):
    list_patching_abs_orbits   = []
    list_patching_dates_sorted = sorted(list_patching_dates, key=lambda x: x['date_start'])
    for patching_period in list_patching_dates_sorted:
        if debug == True:
            logger.info(f'Patching config: {patching_period['swath']} {patching_period['date_start']} to {patching_period['date_end']} station {patching_period['station_id']} and relative orbit {patching_period['relative_orbit']}')
        current = patching_period['date_start']
        end     = patching_period['date_end']

        while current <= end:
            mjd2000_start   = _get_eocfi_mjd2000_from_datetime(current, debug)          
            orbit           = _get_eocfi_orbit_from_mjd2000(mjd2000_start, debug)
            abs_orbit       = orbit['abs_orbit']
            rel_orbit       = xo_orbit_rel_from_abs(abs_orbit, debug)['rel_orbit']
            
            if rel_orbit == patching_period['relative_orbit']:
                if debug == True:
                    logger.info(f'{current.strftime('%Y-%m-%dT%H:%M:%S')} - abs_orbit: {abs_orbit} rel_orbit: {rel_orbit} for {patching_period['station_id']} {patching_period['swath']}')
                patching_abs_orbit              = patching_period.copy()
                patching_abs_orbit['abs_orbit'] = abs_orbit
                patching_abs_orbit['date']      = current
                list_patching_abs_orbits.append(patching_abs_orbit)
            
            '''
            logger.debug(mjd2000_start)
            logger.debug(f"abs_orbit: {abs_orbit} rel_orbit: {rel_orbit}")
            '''
            current += timedelta(minutes = 95)        

    return sorted(list_patching_abs_orbits, key=lambda x: x['abs_orbit'])


import click
CONTEXT_SETTINGS = {"help_option_names": ['-h', '--help'], "max_content_width" : 220}

@click.command(context_settings=CONTEXT_SETTINGS, no_args_is_help = True)
@click.option('--file', '-f',                                            help = 'file MPL_PPF_1_ to be patched')
@click.option('--Config', '-C',      is_flag = True, default = False,    help = 'shows patching configuration')
@click.option('--version', '-v',     is_flag = True, default = False,    help = 'It shows the version')
@click.option('--Silent', '-S',      is_flag = True, default = False,    help = 'Avoid logging messages')
@click.option('--Debug', '-D',       is_flag = True, default = False,    help = 'Debug flag for verbose messages')

def patch_ppf_idle_frames(file: str, config: bool, version: bool, silent: bool, debug: bool):

    """
    \b
    Patch the BMPF MPL_PPF_1 for idle frames transmission according to:
    https://redmineng.exprivia.it/issues/6603
    \b
    """

    if version == True:
        print(f"{os.path.basename(__file__)} - {package_version('bcops')}")
        exit(0)

    list_patching_dates = _init_patching_dates()

    if config == True:
        for patching_date in list_patching_dates:
            logger.info(f'Patching config: {patching_date['swath']} {patching_date['date_start']} to {patching_date['date_end']} station {patching_date['station_id']} and relative orbit {patching_date['relative_orbit']}')
        logger.debug('---------------------------------------------------------------------------')
        _init_eocfi(debug)
        list_patching_abs_orbit = _get_patching_abs_orbit(list_patching_dates)
        logger.info(f'List of patching abs_orbits: {len(list_patching_abs_orbit)}')
        for patching_abs_orbit in list_patching_abs_orbit:
            logger.info(f'{patching_abs_orbit['date'].strftime('%Y%m%d %H:%M')}  abs_orbit: {patching_abs_orbit['abs_orbit']} station {patching_abs_orbit["station_id"]} / relative orbit {patching_abs_orbit["relative_orbit"]} / {patching_abs_orbit['swath']}')
        exit(0)

    if pathlib.Path(f'/data/mpf/BMPF/data/outgoing/MPL_PPF___/{file}').exists() == False:
        logger.error(f'file /data/mpf/BMPF/data/outgoing/MPL_PPF___/{file} not found')
        exit(1)

    if pathlib.Path(f'/data/mpf/BMPF/{file}_PATCHED').exists() == True:
        logger.info(f'It seems {file} has been previously patched')
        logger.error(f'file /data/mpf/BMPF/{file}_PATCHED already exists')
        exit(1)

    if pathlib.Path(f'/data/mpf/BMPF/{file}_ORIGINAL').exists() == True:
        logger.info(f'It seems {file} has been previously patched')
        logger.error(f'file /data/mpf/BMPF/{file}_ORIGINAL already exists')
        exit(1)

    logger.info(f'copy file /data/mpf/BMPF/data/outgoing/MPL_PPF___/{file} to /data/mpf/BMPF/{file}_ORIGINAL')
    shutil.copyfile(f'/data/mpf/BMPF/data/outgoing/MPL_PPF___/{file}', f'/data/mpf/BMPF/{file}_ORIGINAL')

    logger.info(f'copy file /data/mpf/BMPF/data/outgoing/MPL_PPF___/{file} to /data/mpf/BMPF/{file}')
    shutil.copyfile(f'/data/mpf/BMPF/data/outgoing/MPL_PPF___/{file}', f'/data/mpf/BMPF/{file}')

    logger.info(f'patching file /data/mpf/BMPF/{file}')

    fhr = xd_read_fhr(f'/data/mpf/BMPF/{file}')
    val_str_start       = fhr['val_start_date']
    val_str_end         = fhr['val_stop_date']
    val_datetime_start  = datetime.strptime(val_str_start, 'UTC=%Y-%m-%dT%H:%M:%S').replace(tzinfo = ZoneInfo('UTC'))
    val_datetime_end    = datetime.strptime(val_str_end, 'UTC=%Y-%m-%dT%H:%M:%S').replace(tzinfo = ZoneInfo('UTC'))
    
    original_file       = file
    
    for patching_date in list_patching_dates:
        if patching_date['date_start'] <= val_datetime_start and patching_date['date_end'] >= val_datetime_start \
            or patching_date['date_start'] <= val_datetime_end and patching_date['date_end'] >= val_datetime_end:
            cmd = f'bcops_bmpf_downlink_idleframes -s {patching_date['date_start'].strftime('%Y-%m-%dT%H:%M:%S')} -e {patching_date['date_end'].strftime('%Y-%m-%dT%H:%M:%S')} --station-id {patching_date["station_id"]} -o {patching_date["relative_orbit"]} -f /data/mpf/BMPF/{file}'
            logger.info(cmd)
            ret = os.system(cmd)
            if ret != 0:
                logger.error(f'Error running command: {cmd}')
                exit(1)
            file = f'{file}_patched'

    logger.info(f'copy file /data/mpf/BMPF/{file} to /data/mpf/BMPF/{original_file}_PATCHED')
    shutil.copyfile(f'/data/mpf/BMPF/{file}', f'/data/mpf/BMPF/{original_file}_PATCHED')

    logger.info(f'replace file to be sent /data/mpf/BMPF/data/outgoing/MPL_PPF___/{original_file} with patched file /data/mpf/BMPF/{original_file}_PATCHED')
    shutil.copyfile(f'/data/mpf/BMPF/{original_file}_PATCHED', f'/data/mpf/BMPF/data/outgoing/MPL_PPF___/{original_file}')

    exit(0)

# ===========================================================================================================================================================================

def version():
    return package_version('bcops')

if __name__ == '__main__':
    patch_ppf_idle_frames()


exit(0)