#!/usr/bin/env python

'''

'''
import os
import csv as csv_file
from pystac_client import Client
from datetime import datetime, timedelta
import pytz

from loguru import logger
logger = logger.patch(lambda record: record.update(name=record["file"].name))

from importlib.metadata import version as package_version

import click
CONTEXT_SETTINGS = {"help_option_names": ['-h', '--help'], "max_content_width" : 220}

'''
> https://explorer.maap.eo.esa.int
> https://catalog.maap.eo.esa.int/catalogue/collections/BiomassLevel0IOC
> https://catalog.maap.eo.esa.int/catalogue/collections/BiomassLevel1aIOC
> https://catalog.maap.eo.esa.int/catalogue/collections/BiomassLevel1bIOC
> https://catalog.maap.eo.esa.int/catalogue/collections/BiomassLevel0
> https://catalog.maap.eo.esa.int/catalogue/collections/BiomassLevel1a
> https://catalog.maap.eo.esa.int/catalogue/collections/BiomassLevel1b
> https://catalog.maap.eo.esa.int/catalogue/collections/BiomassLevel1c
> https://catalog.maap.eo.esa.int/catalogue/collections/BiomassLevel2a
> https://catalog.maap.eo.esa.int/catalogue/collections/BiomassAux
> https://catalog.maap.eo.esa.int/catalogue/collections/BiomassAuxRest
'''

# BIO_COLLECTIONS     = ['BiomassLevel0IOC', 'BiomassLevel1aIOC', 'BiomassLevel1bIOC', 'BiomassLevel0', 'BiomassLevel1a', 'BiomassLevel1b', 'BiomassLevel1c', 'BiomassLevel2a', 'BiomassAux', 'BiomassAuxRest']
BIO_COLLECTIONS     = ['BiomassLevel0IOC']
list_item_id        = []
list_datatake_id    = []
prev_item_id        = None

@click.command(context_settings=CONTEXT_SETTINGS, no_args_is_help = True)
@click.option('--start', '-s',                                           help = 'start datetime in format YYYY-MM-DDThh:mm:ssZ / 2025-10-22T00:00:00Z')
@click.option('--end', '-e',                                             help = 'end datetime in format YYYY-MM-DDThh:mm:ssZ / 2025-10-23T00:00:00Z')
@click.option('--type', '-t',                                            help = 'API productType filter S1_RAW__0S | S2_RAW__0S | S3_RAW__0S', default = 'S2_RAW__0S')
@click.option('--baseline', '-b',                                        help = 'API product version attribute matching the baseline (e.g. 02)')
@click.option('--CSV', '-C',         is_flag = True, default = False,    help = 'Output results to CSV file')
@click.option('--version', '-v',     is_flag = True, default = False,    help = 'It shows the version')
@click.option('--Silent', '-S',      is_flag = True, default = False,    help = 'Avoid logging messages')
@click.option('--Debug', '-D',       is_flag = True, default = False,    help = 'Debug flag for verbose messages')


def query_datatakes(start: str, end: str, type: str, baseline: str, csv: bool, version: bool, silent: bool, debug: bool):

    """
    \b
    Query MAAP catalogue for data-take information within some time interval and product type within the following collections:
    > BiomassLevel0IOC
    > BiomassLevel1aIOC
    > BiomassLevel1bIOC
    > BiomassLevel0
    > BiomassLevel1a
    > BiomassLevel1b
    > BiomassLevel1c
    > BiomassLevel2a
    > BiomassAux
    > BiomassAuxRest

    CSV file naming convention is:
        bcops_maap_query_datatake_<product_type>_<start_datetime>_<end_datetime>_C<current_datetime>.csv

    CSV file format is:
        datatake_id, product_type, product_id, sensing_start, sensing_end

    Auxiliary products are datatake-less and no grouping is performed.
    \b

    """

    if version == True:
        print(f"{os.path.basename(__file__)} - {package_version('bcops')}")
        exit(0)

    if start is None or end is None:
        print('Error: start and end datetime parameters are required')
        exit(1)

    csv_writer          = None
    str_datetime_start  = start
    str_datetime_end    = end
    date_format         = '%Y-%m-%dT%H:%M:%S%z'
    # time_delta          = timedelta(hours = 1)
    time_delta          = timedelta(hours = 4)

    if type in ['AUX_TEC___', 'AUX_ATT___', 'AUX_ORB___', 'MPL_ORBPRE']:
        time_delta = timedelta(days = 1)
    
    if type in ['AUX_ERP_RD', 'MPL_ORBREF']:
        time_delta = timedelta(days = 7)

    datetime_start      = None
    datetime_end        = None
    
    try:
        datetime_start      = datetime.strptime(str_datetime_start, date_format)
        datetime_end        = datetime.strptime(str_datetime_end, date_format)
    except Exception as e:
        print(f'Error parsing input datetimes: {e}')
        exit(1)

    delta_total = datetime_end - datetime_start

    if delta_total <= time_delta:
        time_delta      = delta_total
        if debug == True:
            logger.debug(f'Query delta interval set to {time_delta}')
        
    datetime_current    = datetime_start
    datetime_now        = datetime.now(pytz.utc)
    filename            = f'bcops_maap_query_datatake_{type}_{datetime_start.strftime("%Y%m%dT%H%M%S")}_{datetime_end.strftime("%Y%m%dT%H%M%S")}_C{datetime_now.strftime("%Y%m%dT%H%M%S")}.csv'
    
    if debug == True and csv == True:
        logger.debug(f'CSV output file: {filename}')
    
    if csv == True:
        file_handler        = open(filename, mode = 'w', newline = '')  
        csv_writer          = csv_file.writer(file_handler, delimiter = ',')
        header              = ['datatake_id', 'product_type', 'product_id', 'sensing_start', 'sensing_end']
        csv_writer.writerow(header)
  
    list_datatake_id        = []

    query_end = datetime_start
    '''
    print(f'datetime_current    {datetime_current}')
    print(f'datetime_start      {datetime_start}')
    print(f'datetime_end        {datetime_end}')
    '''

    while datetime_current < datetime_end:
        if datetime_current + time_delta <= datetime_end:
            query_end += time_delta
        else:
            query_end = datetime_end 
        list_datatake_id += query_biomass_products(datetime_current, query_end, type, baseline, csv_writer, debug)
        datetime_current = query_end

    if csv == True:
        file_handler.close()

    list_datatake_id = list(dict.fromkeys(list_datatake_id))

    for datatake_id in list_datatake_id:
        print(f'{datatake_id}')


def query_biomass_products(datetime_start: datetime, datetime_end: datetime, type: str, baseline: str, csv_writer = None, debug = False):
    global list_item_id
    global prev_item_id
    bio_collections = []
    date_format        = '%Y-%m-%dT%H:%M:%SZ %:z'
    str_datetime_start = datetime_start.strftime(date_format)
    str_datetime_end   = datetime_end.strftime(date_format)
    URL_LANDING_PAGE   = 'https://catalog.maap.eo.esa.int/catalogue/'
    datetime_tom_phase = datetime(2025, 11, 21, 0, 29, 45, tzinfo = pytz.utc)

    if type[-7:] == 'RAW__0S' and datetime_end >= datetime_tom_phase and datetime_start < datetime_tom_phase:
        bio_collections = ['BiomassLevel0IOC', 'BiomassLevel0']

    if type[-7:] == 'RAW__0S' and datetime_end < datetime_tom_phase:
        bio_collections = ['BiomassLevel0IOC']

    if type[-7:] == 'RAW__0S' and datetime_end >= datetime_tom_phase:
        bio_collections = ['BiomassLevel0']

    if type[-7:] == 'SCS__1S' and datetime_end >= datetime_tom_phase and datetime_start < datetime_tom_phase:
        bio_collections = ['BiomassLevel1aIOC', 'BiomassLevel1a']

    if type[-7:] == 'SCS__1S' and datetime_end < datetime_tom_phase:
        bio_collections = ['BiomassLevel1aIOC']

    if type[-7:] == 'SCS__1S' and datetime_end >= datetime_tom_phase:
        bio_collections = ['BiomassLevel1a']

    if type[-7:] == 'DGM__1S' and datetime_end >= datetime_tom_phase and datetime_start < datetime_tom_phase:
        bio_collections = ['BiomassLevel1bIOC', 'BiomassLevel1b']

    if type[-7:] == 'DGM__1S' and datetime_end < datetime_tom_phase:
        bio_collections = ['BiomassLevel1bIOC']

    if type[-7:] == 'DGM__1S' and datetime_end >= datetime_tom_phase:
        bio_collections = ['BiomassLevel1b']

    if type[-7:] == 'STA__1S' and datetime_end >= datetime_tom_phase and datetime_start < datetime_tom_phase:
        bio_collections = ['BiomassLevel1cIOC', 'BiomassLevel1c']

    if type[-7:] == 'STA__1S' and datetime_end < datetime_tom_phase:
        bio_collections = ['BiomassLevel1cIOC']

    if type[-7:] == 'STA__1S' and datetime_end >= datetime_tom_phase:
        bio_collections = ['BiomassLevel1c']

    if type == 'FP_GN__L2A' and datetime_end >= datetime_tom_phase:
        bio_collections = ['BiomassLevel2a']

    if type == 'FP_FD__L2A' and datetime_end >= datetime_tom_phase:
        bio_collections = ['BiomassLevel2a']

    if type == 'FP_FH__L2A' and datetime_end < datetime_tom_phase:
        bio_collections = ['BiomassLevel2a']

    if type[-7:] == '_ERP_RD':
        bio_collections = ['BiomassAuxRestIOC', 'BiomassAuxRest']

    if type[-7:] == '_TEC___':
        bio_collections = ['BiomassAuxRestIOC', 'BiomassAuxRest']

    if debug == True:
        logger.debug(f'Connecting to {URL_LANDING_PAGE}')
    
    api = None
    try:
        api  = Client.open(URL_LANDING_PAGE)
    except Exception as e:
        logger.error(f"Error when connecting to {URL_LANDING_PAGE}")
        logger.error(f"{e}")
        exit(1)
    
    if debug == True:
        logger.debug(f'{str_datetime_start} to {str_datetime_end} => querying {type} products in collections {bio_collections}')

    results = None

    if baseline is not None:
        results = api.search(
            method      = "GET",
            collections = bio_collections,
            filter      = f"productType='{type}' and version='{baseline}'",
            datetime    = [datetime_start, datetime_end]
        )
    else:
        results = api.search(
            method      = "GET",
            collections = bio_collections,
            filter      = f"productType='{type}'",
            datetime    = [datetime_start, datetime_end]
        )

    items = []
    try:
        items = list(results.items())
    except Exception as e:
        logger.error(f"Error when querying {type} products between {str_datetime_start} and {str_datetime_end}")
        logger.error(f"{e}")
        exit(1)

    if len(items) == 0:
        if debug == True:
            logger.debug(f'No items found between {str_datetime_start} and {str_datetime_end}')
        return []
    
    items.sort( key = lambda x : x.properties['start_datetime'] )
    
    date_format_ms  = '%Y-%m-%dT%H:%M:%S.%fZ'
    granule_start   = datetime.strptime(items[0].properties['start_datetime'], date_format_ms)
    granule_end     = datetime.strptime(items[0].properties['end_datetime'], date_format_ms)

    'Auxiliary products may not have datatake_id property'
    datatake_id = None
    try:
        datatake_id = items[0].properties['eopf:datatake_id']
    except KeyError:
        datatake_id = 'N/A'

    for item in items:
        current_datatake_id = None
        try:
            current_datatake_id = item.properties['eopf:datatake_id']
        except KeyError:
            current_datatake_id = 'N/A'

        if current_datatake_id not in list_datatake_id:
            if debug == True:
                logger.debug(f"datatake#{current_datatake_id}")
            list_datatake_id.append(current_datatake_id)
        
        if debug == True and item.id != prev_item_id:
            logger.debug(f"ID: {item.id}, Type: {item.properties['product:type']}, Datatake: {current_datatake_id}, Start: {item.properties['start_datetime']}, End: {item.properties['end_datetime']}")

        if csv_writer is not None:
            if item.id not in list_item_id:
            # search by previous is not safe if query delta-time is shorter than product(s) overlap
            # if prev_item_id != item.id: 
                row = [
                    current_datatake_id,
                    item.properties['product:type'],
                    item.id,
                    item.properties['start_datetime'],
                    item.properties['end_datetime']
                ]
                csv_writer.writerow(row)
                list_item_id.append(item.id)
 
        current_start    = datetime.strptime(item.properties['start_datetime'], date_format_ms)
        current_end      = datetime.strptime(item.properties['end_datetime'], date_format_ms)

        if current_datatake_id == datatake_id:
            if (current_start < granule_start) or (current_end < granule_end):
                logger.warning(f'discontinuity detected for datatake {current_datatake_id}')        
        datatake_id   = current_datatake_id
        granule_start = current_start
        granule_end   = current_end
        prev_item_id  = item.id

    return list_datatake_id


def version():
    return package_version('bcops')

if __name__ == '__main__':
    query_datatakes()


exit(0)