#!/usr/bin/env python

import os
import sys
import importlib
import pathlib
import traceback

from datetime import datetime


from loguru import logger
logger = logger.patch(lambda record: record.update(name=record["file"].name))

from importlib.metadata import version as package_version

import click
CONTEXT_SETTINGS = {"help_option_names": ['-h', '--help'], "max_content_width" : 220}

@click.command(context_settings=CONTEXT_SETTINGS, no_args_is_help = True)
@click.option('--id', '-i',                                              help = 'GROUND USER ANNOTATION to decode (e.g. 2190366208)')
@click.option('--config', '-c',      is_flag = True, default = False,    help = 'It shows the configuration')
@click.option('--version', '-v',     is_flag = True, default = False,    help = 'It shows the version')
@click.option('--Silent', '-S',      is_flag = True, default = False,    help = 'Avoid logging messages')
@click.option('--Debug', '-D',       is_flag = True, default = False,    help = 'Debug flag for verbose messages')


def decode_ground_user_annotation(id: str, config: bool, version: bool, silent: bool, debug: bool):

    """
    \b
    Decode the GROUND USER ANNOTATION according to ESA-EOPG-EOEP-TN-41 encoded by BMPF as a raw integer 32 bits
    \b

    """

    # The Ground User Annotation is encoded into 32 bits as follows:
    # 0-1: Phase (2 bits)
    # 2: Drift (1 bit)
    # 3-6: Global Coverage (4 bits)
    # 7-10: Major Cycle (4 bits)
    # 11-14: Repeat Cycle (4 bits)
    # 15-22: Track Number (8 bits)
    # 23-24: Calibration (2 bits)

    # Extracting the first (most significant) 19 bits of a 32-bit value is equivalent to right-shifting the number by 32 - 19 = 13 bits.
    # echo $((48038273 >> 13))
    # Extracting the last (least significant) 13 bits is a masking operation: value & (2^13 - 1)
    # 0x1FFF = 8191 = 2^13 - 1

    ground_user_annotation = int(id)
    hex_str_big_endian = hex(ground_user_annotation)[2:].zfill(8)
    phase = ground_user_annotation >> 30
    drift = (ground_user_annotation >> 29) & 1
    global_coverage = (ground_user_annotation >> 25) & 0xF
    major_cycle = (ground_user_annotation >> 21) & 0xF
    repeat_cycle = (ground_user_annotation >> 17) & 0xF
    track_number = (ground_user_annotation >> 9) & 0xFF
    calibration = (ground_user_annotation >> 7) & 0x3
    '''
    print(f'Ground User Annotation: {ground_user_annotation} (0x{hex_str_big_endian})')
    print(phase)
    print(drift)
    print(global_coverage)
    print(major_cycle)
    print(repeat_cycle)
    print(track_number)
    print(calibration)
    '''
    logger.info(f'0x{hex_str_big_endian}: phase: {phase} - drift: {drift} - global coverage: {global_coverage} - major cycle: {major_cycle} - repeat cycle: {repeat_cycle} - track number: {track_number} - calibration: {calibration}')

    
def version():
    return package_version('bcops')

if __name__ == '__main__':
    decode_ground_user_annotation()


exit(0)