#!/usr/bin/env python

import os
import sys
import shutil
import importlib
import pathlib
import traceback

from lxml       import etree
from datetime   import datetime

try:
    import eocfi
except Exception as e:
    print(f'Error importing eocfi: {e}')
    print(f'Please install eocfi:') 
    print('https://eop-cfi.esa.int/index.php/mission-cfi-software/eocfi-software')
    exit(1)

from eocfi.constants import XL_ASCII_CCSDSA
from eocfi.constants import XL_PROC
from eocfi.constants import XL_TIME_UTC
from eocfi.constants import XV_FILE_STF
from eocfi.constants import XL_MODEL_DEFAULT
from eocfi.constants import XF_HEADER_FORMAT_EOF

from eocfi.api    import version as eocfi_version
from eocfi.api_xo import xo_check_library_version
from eocfi.api_xd import xd_read_station_id
from eocfi.api_xd import xd_read_station
from eocfi.api_xd import xd_read_osf
from eocfi.api_xl import xl_model_init
from eocfi.api_xl import xl_time_ref_init_file
from eocfi.api_xl import xl_time_ascii_to_processing
from eocfi.api_xl import xl_time_processing_to_ascii
from eocfi.api_xo import xo_orbit_init_file
from eocfi.api_xo import xo_orbit_get_val_time
from eocfi.api_xo import xo_orbit_rel_from_abs
from eocfi.api_xo import xo_orbit_close
from eocfi.api_xo import xo_verbose
from eocfi.api_xv import xv_swath_id_init
from eocfi.api_xv import xv_stationvistime_compute
from eocfi.api_xf import xf_tree_create
from eocfi.api_xf import xf_tree_create_root
from eocfi.api_xf import xf_tree_create_header
from eocfi.api_xf import xf_tree_set_fixed_header_items
from eocfi.api_xf import xf_tree_add_child
from eocfi.api_xf import xf_tree_add_next_sibling
from eocfi.api_xf import xf_tree_add_attribute
from eocfi.api_xf import xf_tree_set_string_node_value
from eocfi.api_xf import xf_tree_write

from loguru import logger
logger = logger.patch(lambda record: record.update(name=record["file"].name))

from importlib.metadata import version as package_version

import click
CONTEXT_SETTINGS = {"help_option_names": ['-h', '--help'], "max_content_width" : 220}

@click.command(context_settings=CONTEXT_SETTINGS, no_args_is_help = True)
@click.option('--file', '-f',                                            help = 'file MPL_PPF_1_ to be patched')
@click.option('--start', '-s',                                           help = 'start datetime in format YYYY-MM-DDThh:mm:ss / 2025-11-22T00:00:00')
@click.option('--end', '-e',                                             help = 'end datetime in format YYYY-MM-DDThh:mm:ss / 2027-03-30T00:00:00')
@click.option('--station-id',                                            help = 'station id to create the AF unavailability')
@click.option('--rel-orbit', '-o',                                       help = 'relative orbit number to create the AF unavailability')
@click.option('--list', '-l',        is_flag = True, default = False,    help = 'list all X-band ground stations')
@click.option('--config', '-c',      is_flag = True, default = False,    help = 'It shows the configuration')
@click.option('--version', '-v',     is_flag = True, default = False,    help = 'It shows the version')
@click.option('--Silent', '-S',      is_flag = True, default = False,    help = 'Avoid logging messages')
@click.option('--Debug', '-D',       is_flag = True, default = False,    help = 'Debug flag for verbose messages')


def downlink_idle_frames(file: str, start: str, end: str, station_id: str, rel_orbit: str, list: bool, config: bool, version: bool, silent: bool, debug: bool):

    """
    \b
    Process PDGS Payload Plan to BIO-ESA-EOPG-EEGS-ID-0079 to modify the X-band downlink plan for just transmission of idle frames only.

    The PDHU memory playback/stop/deletion requests are removed for the modified passes

    The downlink passes for a given --station-id are selected based on the relative orbit of the repeat cycle qualified by --rel-orbit  
    \b

    """

    if version == True:
        print(f"{os.path.basename(__file__)} - {package_version('bcops')}")
        print(f'eocfi - {eocfi_version()}')
        xo_check_library_version()
        exit(0)

    dist                = importlib.metadata.distribution('eocfi')
    root_dist_info      = dist._path
    dist_info_dir       = pathlib.Path(dist._path).parent
    package_root_dir    = f'{dist_info_dir}/bcops'

    file_orbsct       = f'{dist_info_dir}/bcops/data/BIO_COPS_MPL_ORBSCT'
    file_orbref       = f'{dist_info_dir}/bcops/data/BIO_OPER_MPL_ORBREF_20251121T000000_20270331T000000_0006.EOF'
    file_gnd_db       = f'{dist_info_dir}/bcops/data/BIO_OPER_MPL_GND_DB_00000000T000000_99999999T999999_STATIONS_0001.EOF'

    if config == True:
        print(file_gnd_db)
        print(file_orbref)
        print(file_orbsct)
        exit(0)
   
    list_input_files = []
    list_input_files.append(os.path.splitext(os.path.basename(file_gnd_db))[0])
    list_input_files.append(os.path.splitext(os.path.basename(file_orbref))[0])
    list_input_files.append(os.path.splitext(os.path.basename(file_orbsct))[0])

    if list == True and station_id != None:
        print(f'Flag --List is incompatible with --station-id {station_id}')
        exit(99)

    if debug == True:
        logger.info(f'xd_read_station_id => {file_gnd_db}')
    list_station_id = xd_read_station_id(file_gnd_db)

    if debug == True:
        logger.info(f'xd_read_station {station_id}')

    if list == True:
        for station_id in list_station_id:
            station_info = xd_read_station(file_gnd_db, station_id, debug)
            logger.info(f'Ground Station: {station_info['station_id']}')
            logger.info(station_info['antenna'])
            logger.info(station_info['descriptor'])
            logger.info(station_info['purpose'])
            
        exit(0)

    if file == None:
        print(f"Error: --file is mandatory")
        exit(66)

    if os.path.exists(file) == False:
        print(f"Error: file {file} does not exist")
        exit(99)

    if os.path.basename(file)[9:19] != 'MPL_PPF_1_':
        print(f"Error: file {os.path.basename(file)} with file-type {os.path.basename(file)[9:19]} is not supported")
        exit(99)

    if station_id == None:
        print(f"Error: --station-id is mandatory")
        exit(66)

    if rel_orbit == None:
        print(f"Error: --rel-orbit is mandatory")
        exit(66)

    if station_id not in list_station_id:
        print(f'Error --station-id {station_id} not present in {file_gnd_db}')
        exit(99)

    station_info = xd_read_station(file_gnd_db, station_id, debug)
    
    if debug == True:
        logger.info(station_info['station_id'])
        logger.info(station_info['descriptor'])
        logger.info(station_info['purpose'])
        logger.info(station_info['antenna'])

    try:
        rel_orbit = int(rel_orbit)
    except:
        print('Error: rel-orbit must be an integer value')
        exit(1)

    osf             = xd_read_osf(file_orbsct)
    cycle_orbits    = int( osf[0]['cycle_orbits'] )

    if rel_orbit > cycle_orbits:
        print(f'Error --rel-orbit {rel_orbit} not in range between 1..{cycle_orbits}')
        exit(99)

    str_date_start  = start
    str_date_stop   = end
    date_format            = '%Y-%m-%dT%H:%M:%S'
    date_start             = None
    date_stop              = None

    if str_date_start != None:
        try:
            date_start = datetime.strptime(str_date_start, date_format)
        except Exception as e:
            print(f'Error parsing start input datetime: {e}')
            exit(99)

    if str_date_stop != None:
        try:
            date_stop = datetime.strptime(str_date_stop, date_format)
        except Exception as e:
            print(f'Error parsing start input datetime: {e}')
            exit(99)

    # Variables for time conversion
    ascii_id_out        = XL_ASCII_CCSDSA
    time_ref_in         = XL_TIME_UTC
    proc_id_in          = XL_PROC
    time_ref_out        = XL_TIME_UTC  
    mode                = XL_MODEL_DEFAULT

    if debug == True:
        logger.info(f'xl_time_ascii_to_processing => {str_date_start}')

    ascii_id_in         = XL_ASCII_CCSDSA
    time_ref_in         = XL_TIME_UTC
    ascii_in            = str_date_start
    proc_id_out         = XL_PROC
    time_ref_out        = XL_TIME_UTC
    processing_out      = None
    
    if str_date_start != None:
        processing_out = xl_time_ascii_to_processing(
                                        ascii_id_in,
                                        time_ref_in,
                                        ascii_in,
                                        proc_id_out,
                                        time_ref_out,
                                        debug)

    mjd2000_start = processing_out

    if debug == True:
        logger.debug(f'xl_time_ascii_to_processing {str_date_start} => {mjd2000_start}')

    ascii_in       = str_date_stop

    if str_date_stop != None:
        processing_out = xl_time_ascii_to_processing(
                                        ascii_id_in,
                                        time_ref_in,
                                        ascii_in,
                                        proc_id_out,
                                        time_ref_out,
                                        debug)

    mjd2000_end = processing_out

    if start != None and end != None and (mjd2000_start > mjd2000_end):
        print(f'Error --start: {start} cannot be later than --end {end}')
        exit(99)

    if debug == True:
        logger.info(f'xl_model_init')
    
    xl_model_init(mode, debug)
    
    if debug == True:
        logger.info(f'xl_time_ref_init_file {file_orbref}')
    try:
        xl_time_ref_init_file(file_orbref, debug)
    except Exception as error:
        logger.error(f"Failed to init the time reference xl_time_ref_init_file with file {file_orbref}")
        logger.error(error)
        exit(99)

    if debug == True:
        logger.info(f'xo_verbose')
        xo_verbose(debug)

    if debug == True:
        logger.info(f'xo_orbit_init_file {file_orbref}')
    try:
        xo_orbit_init_file(file_orbref, debug)
    except Exception as error:
        logger.error(f"Failed to init the orbit reference xo_orbit_init_file with file {file_orbref}")
        logger.error(error)
        if debug == True:
            print(traceback.format_exc())
        exit(99)
    
    if debug == True:
        logger.info(f'xo_orbit_get_val_time')
    xo_validity_time = xo_orbit_get_val_time(debug)
    
    if debug == True:
        logger.info(xo_validity_time)

    if (str_date_start != None and str_date_stop != None) and (mjd2000_end > xo_validity_time['stop'] or mjd2000_start < xo_validity_time['start']):
        logger.error(f'interval [{mjd2000_start},{mjd2000_end}] is out of range of orbit validity interval [{xo_validity_time['start']},{xo_validity_time['stop']}]')
        exit(99)

    if debug == True:
        logger.info(f'xo_orbit_close')

    xo_orbit_close(debug)

    if debug == True:
        logger.info(f'xo_orbit_init_file {file_orbsct}')
    try:
        xo_orbit_init_file(file_orbsct, debug)
    except Exception as error:
        logger.error(f"Failed to init the orbit scenario xo_orbit_init_file with file {file_orbsct}")
        logger.error(error)
        if debug == True:
            print(traceback.format_exc())
        exit(99)

    LIST_OF_MEMORY_REQUEST  = ['DUMP_HHV', 'DUMP_HVH', 'DUMP_HK_', 'STOPDUMP', 'FREE_HK_', 'FREE_H__', 'FREE_V__'] 
    file_ppf_1_original     = file
    file_ppf_1              = f'{file}_patched'
    shutil.copy(file_ppf_1_original, file_ppf_1)
    
    logger.info(f'Generating the file {file_ppf_1}')
    
    xml_ppf_1               = etree.parse(file_ppf_1)
    root_ppf_1              = xml_ppf_1.getroot()
    path                    = '/Earth_Explorer_File/Earth_Explorer_Header/Fixed_Header/Notes'
    fixed_header_notes      = root_ppf_1.xpath(path)

    if len(fixed_header_notes) > 0:
        fixed_header_notes_text = fixed_header_notes[0].text

    if fixed_header_notes_text is None:
        fixed_header_notes_text = ''

    if debug == True:
        logger.debug(f"Fixed Header Notes: {fixed_header_notes_text}")
    
    path                    = '/Earth_Explorer_File/Data_Block/List_of_EVRQs/EVRQ'
    list_of_evrqs           = root_ppf_1.xpath(path)

    if debug == True:
        logger.debug(f"Number of EVRQs: {len(list_of_evrqs)}")
    
    for evrq in list_of_evrqs:
        path    = 'RQ/RQ_Name'
        rq_name = evrq.xpath(path)
        if len(rq_name) == 0:
            continue
        rq_name = rq_name[0].text
        if rq_name not in LIST_OF_MEMORY_REQUEST:
            continue
        
        path            = 'RQ/RQ_Absolute_orbit'
        rq_abs_orbit    = int(evrq.xpath(path)[0].text)
        rq_rel_orbit    = int(xo_orbit_rel_from_abs(rq_abs_orbit)['rel_orbit'])

        if rq_rel_orbit != rel_orbit:
            continue

        path                = 'RQ/RQ_Execution_Time'
        rq_exec_time        = evrq.xpath(path)[0].text
        date_rq_exec_time   = datetime.strptime(rq_exec_time, 'UTC=%Y-%m-%dT%H:%M:%S.%f')
        
        if date_start != None and date_rq_exec_time < date_start:
            logger.info(f"Skipping RQ_Name: {rq_name} at {rq_exec_time} / RQ_Absolute_orbit: {rq_abs_orbit} / RQ_Relative_orbit: {rq_rel_orbit} before start date")
            continue

        if date_stop != None and date_rq_exec_time > date_stop:
            logger.info(f"Skipping RQ_Name: {rq_name} at {rq_exec_time} / RQ_Absolute_orbit: {rq_abs_orbit} / RQ_Relative_orbit: {rq_rel_orbit} after end date")
            continue

        if f'Patched passes to transmit idle frames only for {station_id}:' not in fixed_header_notes_text:
            fixed_header_notes_text += f'\n         Patched passes to transmit idle frames only for {station_id}:'

        if str(rq_abs_orbit) not in fixed_header_notes_text:
            fixed_header_notes_text += f' {rq_abs_orbit}'

        logger.info(f"Removing RQ_Name: {rq_name} at {rq_exec_time} / RQ_Absolute_orbit: {rq_abs_orbit} / RQ_Relative_orbit: {rq_rel_orbit}")    

        parent = evrq.getparent()
        parent.remove(evrq)
    
    logger.info(f"Number of EVRQs after removal: {len(root_ppf_1.xpath('/Earth_Explorer_File/Data_Block/List_of_EVRQs/EVRQ'))}")
    root_ppf_1.xpath('/Earth_Explorer_File/Data_Block/List_of_EVRQs')[0].set('count', str(len(root_ppf_1.xpath('/Earth_Explorer_File/Data_Block/List_of_EVRQs/EVRQ'))))
    fixed_header_notes[0].text = fixed_header_notes_text
    xml_ppf_1.write(file_ppf_1, xml_declaration = True, pretty_print = True, encoding = 'utf-8')

# ===========================================================================================================================================================================

def version():
    return package_version('bcops')

if __name__ == '__main__':
    downlink_idle_frames()

exit(0)