#!/usr/bin/env python

from multiprocessing.util import debug
import os
import sys
import importlib
import pathlib
import traceback

from datetime import datetime, timedelta

try:
    import eocfi
except Exception as e:
    print(f'Error importing eocfi: {e}')
    print(f'Please install eocfi:') 
    print('https://eop-cfi.esa.int/index.php/mission-cfi-software/eocfi-software')
    exit(1)

from eocfi.constants import XL_ASCII_CCSDSA
from eocfi.constants import XL_PROC
from eocfi.constants import XL_TIME_UTC
from eocfi.constants import XV_FILE_STF
from eocfi.constants import XL_MODEL_DEFAULT
from eocfi.constants import XF_HEADER_FORMAT_EOF

from eocfi.api    import version as eocfi_version
from eocfi.api_xo import xo_check_library_version
from eocfi.api_xd import xd_read_zone
from eocfi.api_xd import xd_read_zone_id
from eocfi.api_xl import xl_model_init
from eocfi.api_xl import xl_time_ref_init_file
from eocfi.api_xl import xl_time_ascii_to_processing
from eocfi.api_xl import xl_time_processing_to_ascii
from eocfi.api_xl import xl_time_close
from eocfi.api_xo import xo_orbit_init_file
from eocfi.api_xo import xo_orbit_get_val_time
from eocfi.api_xo import xo_orbit_rel_from_abs
from eocfi.api_xo import xo_orbit_close
from eocfi.api_xo import xo_verbose
from eocfi.api_xv import xv_swath_id_init
from eocfi.api_xv import xv_zonevistime_compute
from eocfi.api_xv import xv_swath_id_close

from eocfi.api_xp import xp_atmos_init
from eocfi.api_xf import xf_tree_create
from eocfi.api_xf import xf_tree_create_root
from eocfi.api_xf import xf_tree_create_header
from eocfi.api_xf import xf_tree_set_fixed_header_items
from eocfi.api_xf import xf_tree_add_child
from eocfi.api_xf import xf_tree_add_next_sibling
from eocfi.api_xf import xf_tree_add_attribute
from eocfi.api_xf import xf_tree_set_string_node_value
from eocfi.api_xf import xf_tree_write
from eocfi.constants import XV_FILE_STF
from eocfi.constants import XP_STD_INIT

import bcops.bcops_bmpf_parse_misstl as parser_misstl

from loguru import logger
logger = logger.patch(lambda record: record.update(name=record["file"].name))

from importlib.metadata import version as package_version

TIME_DELTA_SRM_ENTRY    = timedelta(days = 0.5)
TIME_DELTA_SRM_EXIT     = timedelta(days = 2.5)

import click
CONTEXT_SETTINGS = {"help_option_names": ['-h', '--help'], "max_content_width" : 220}

@click.command(context_settings=CONTEXT_SETTINGS, no_args_is_help = True)
@click.option('--start', '-s',                                           help = 'start datetime in format YYYY-MM-DDThh:mm:ss / 2025-11-22T00:00:00')
@click.option('--end', '-e',                                             help = 'end datetime in format YYYY-MM-DDThh:mm:ss / 2027-04-07T00:00:00')
@click.option('--config', '-c',      is_flag = True, default = False,    help = 'It shows the configuration')
@click.option('--version', '-v',     is_flag = True, default = False,    help = 'It shows the version')
@click.option('--Silent', '-S',      is_flag = True, default = False,    help = 'Avoid logging messages')
@click.option('--Debug', '-D',       is_flag = True, default = False,    help = 'Debug flag for verbose messages')


def generate_bct_pass(start: str, end: str, config: bool, version: bool, silent: bool, debug: bool):

    """
    \b
    Compute the BCT passes / opportunities.
    \b

    """

    if version == True:
        print(f"{os.path.basename(__file__)} - {package_version('bcops')}")
        print(f'eocfi - {eocfi_version()}')
        xo_check_library_version()
        exit(0)

    dist              = importlib.metadata.distribution('eocfi')
    root_dist_info    = dist._path
    dist_info_dir     = pathlib.Path(dist._path).parent
    package_root_dir  = f'{dist_info_dir}/bcops'

    file_orbsct       = f'{dist_info_dir}/bcops/data/BIO_COPS_MPL_ORBSCT'
    file_orbref       = f'{dist_info_dir}/bcops/data/BIO_OPER_MPL_ORBREF_20251121T000000_20270409T000000_0009.EOF'
    file_swtssp       = f'{dist_info_dir}/bcops/data/BIO_OPER_MPL_SWTREF_20251121T000514_20270407T222259_GNDTRACK_0001.EOF'
    file_swt_1        = f'{dist_info_dir}/bcops/data/BIO_OPER_MPL_SWTREF_20251121T000514_20270407T222259_SW1_CAL__0001.EOF'
    file_swt_2        = f'{dist_info_dir}/bcops/data/BIO_OPER_MPL_SWTREF_20251121T000514_20270407T222259_SW2_CAL__0001.EOF'
    file_swt_3        = f'{dist_info_dir}/bcops/data/BIO_OPER_MPL_SWTREF_20251121T000514_20270407T222259_SW3_CAL__0001.EOF'
    file_swt_srm      = f'{dist_info_dir}/bcops/data/BIO_OPER_MPL_SWTREF_20251121T000514_20270407T222259_SRM_CAL__0001.EOF'
    file_misstl       = f'{dist_info_dir}/bcops/data/BIO_OPER_MPL_MISSTL_20251121T002945_20270409T003354_TOM______0001.EOF'
    file_gndbct       = f'{dist_info_dir}/bcops/data/BIO_OPER_MPL_ZON_DB_00000000T000000_99999999T999999_BCT______0001.EOF'
    zone_id           = 'BCT'

    if config == True:
        logger.info(os.path.basename(file_orbref))
        logger.info(os.path.basename(file_orbsct))
        logger.info(os.path.basename(file_misstl))
        logger.info(os.path.basename(file_gndbct))
        logger.info(os.path.basename(file_swt_1))
        logger.info(os.path.basename(file_swt_2))
        logger.info(os.path.basename(file_swt_3))
        logger.info(os.path.basename(file_swt_srm))
        zone = xd_read_zone(file_gndbct, zone_id, debug)
        logger.info(zone)
        exit(0)

    list_input_files = []
    list_input_files.append(os.path.splitext(os.path.basename(file_gndbct))[0])
    list_input_files.append(os.path.splitext(os.path.basename(file_orbref))[0])
    list_input_files.append(os.path.splitext(os.path.basename(file_swtssp))[0])
    list_input_files.append(os.path.splitext(os.path.basename(file_orbsct))[0])

    if start is None or end is None:
        print('Error: start and end datetime parameters are required')
        exit(1)

    str_datemjd2000_start   = start
    str_datemjd2000_end     = end
    date_format             = '%Y-%m-%dT%H:%M:%S'
    datetime_start          = None
    datetime_end            = None
    
    try:
        datetime_start      = datetime.strptime(str_datemjd2000_start, date_format)
        datetime_end        = datetime.strptime(str_datemjd2000_end, date_format)
    except Exception as e:
        print(f'Error parsing input datetimes: {e}')
        exit(1)

    if debug == True:
        logger.info('xd_read_zone_id')
    list_zone_id = xd_read_zone_id(file_gndbct, debug)
    zone_id      = list_zone_id[0]
    xd_read_zone(file_gndbct, zone_id, debug)
    if debug == True:
        logger.info(f'Processing zone {zone_id}')

    # Variables for time conversion
    ascii_id_out        = XL_ASCII_CCSDSA
    time_ref_in         = XL_TIME_UTC
    proc_id_in          = XL_PROC
    time_ref_out        = XL_TIME_UTC  
    mode                = XL_MODEL_DEFAULT

    if debug == True:
        logger.info(f'xl_time_ascii_to_processing => {str_datemjd2000_start}')

    ascii_id_in         = XL_ASCII_CCSDSA
    time_ref_in         = XL_TIME_UTC
    ascii_in            = str_datemjd2000_start
    proc_id_out         = XL_PROC
    time_ref_out        = XL_TIME_UTC
    processing_out      = None
    processing_out      = xl_time_ascii_to_processing(
                                        ascii_id_in,
                                        time_ref_in,
                                        ascii_in,
                                        proc_id_out,
                                        time_ref_out,
                                        debug)
    mjd2000_start       = processing_out

    if debug == True:
        logger.debug(f'xl_time_ascii_to_processing {str_datemjd2000_start} => {mjd2000_start}')

    ascii_in       = str_datemjd2000_end
    processing_out = xl_time_ascii_to_processing(
                                        ascii_id_in,
                                        time_ref_in,
                                        ascii_in,
                                        proc_id_out,
                                        time_ref_out,
                                        debug)

    mjd2000_end     = processing_out
    swath_mode      = XV_FILE_STF
    atmos_init_mode = XP_STD_INIT
    atmos_model     = 0
    atmos_init_file = None

    if debug == True:
        logger.info('xl_model_init')
    xl_model_init(XL_MODEL_DEFAULT, debug)

    if debug == True:
        logger.info(f'xl_time_ref_init_file => {file_orbref}')
    xl_time_ref_init_file(file_orbref, debug)

    if debug == True:
        logger.info(f'xo_orbit_init_file => {file_orbref}')
    xo_orbit_init_file(file_orbref, debug)

    if debug == True:
        logger.info('xp_atmos_init')
    xp_atmos_init(atmos_init_mode, atmos_model, atmos_init_file, debug)

    dict_file_swath = {}
    dict_file_swath['Swath_1']  = file_swt_1
    dict_file_swath['Swath_2']  = file_swt_2
    dict_file_swath['Swath_3']  = file_swt_3
    dict_file_swath['SRM']      = file_swt_srm

    list_swath = parser_misstl.parse_mission_timeline_swath_cycle(file_misstl, logger, debug)

    current_datetime_start      = datetime_start
    current_datetime_end        = datetime_end

    for swath in list_swath:
        if debug == True:
            logger.debug(f'Swath ID: {swath["id"]} / Start: {swath["Start_Time"]} / Stop: {swath["Stop_Time"]}')

        if datetime_end < swath["Stop_Time"]:
            current_datetime_end = datetime_end
        else:
            current_datetime_end = swath["Stop_Time"]
        query_bct_pass(current_datetime_start, current_datetime_end, file_gndbct, dict_file_swath[swath['id']], zone_id, swath, debug)
        if current_datetime_end < swath["Stop_Time"]:
            break
        else:
            current_datetime_start = swath["Stop_Time"]

    if debug == True:
        logger.info('xo_orbit_close')
    xo_orbit_close()

    if debug == True:
        logger.info('xl_time_close')
    xl_time_close()

    exit(0)

# ===========================================================================================================================================================================

def query_bct_pass(datetime_start: datetime, datetime_end: datetime, file_gndbct: str, file_swath: str, zone_id: str, swath: dict, debug: bool):
    if debug == True:
        logger.info(f'Processing BCT in {os.path.basename(file_gndbct)} [{datetime_start} to {datetime_end}] => {file_swath} - {swath['id']}')
    
    global TIME_DELTA_SRM_ENTRY
    global TIME_DELTA_SRM_EXIT

    if debug == True:
        logger.info(f'xv_swath_id_init => {os.path.basename(file_swath)}')
    swath_mode      = XV_FILE_STF
    xv_swath_id_init(swath_mode, file_swath, debug)

    if debug == True:
        logger.info(f'xl_time_ascii_to_processing => {datetime_start.strftime("%Y-%m-%dT%H:%M:%S")}')

    ascii_id_in         = XL_ASCII_CCSDSA
    ascii_id_out        = XL_ASCII_CCSDSA
    time_ref_in         = XL_TIME_UTC
    time_ref_out        = XL_TIME_UTC
    ascii_in            = datetime_start.strftime('%Y-%m-%dT%H:%M:%S')
    proc_id_in          = XL_PROC
    proc_id_out         = XL_PROC
    processing_out      = None
    processing_out      = xl_time_ascii_to_processing(
                                        ascii_id_in,
                                        time_ref_in,
                                        ascii_in,
                                        proc_id_out,
                                        time_ref_out,
                                        debug)
    mjd2000_start       = processing_out

    if debug == True:
        logger.debug(f'xl_time_ascii_to_processing => {datetime_end.strftime("%Y-%m-%dT%H:%M:%S")}')

    ascii_in       = datetime_end.strftime('%Y-%m-%dT%H:%M:%S')
    processing_out = xl_time_ascii_to_processing(
                                        ascii_id_in,
                                        time_ref_in,
                                        ascii_in,
                                        proc_id_out,
                                        time_ref_out,
                                        debug)
    mjd2000_end     = processing_out

    list_zone_vis = []
    if debug == True:
        logger.info(f'xv_zonevistime_compute => {zone_id}')
    try:
        list_zone_vis = xv_zonevistime_compute(file_gndbct, zone_id, mjd2000_start, mjd2000_end, debug)
    except Exception as error:
        logger.error(f"Failed xv_zonevistime_compute {zone_id}")

    for bct_vis in list_zone_vis:
        start_orbit         = bct_vis['xv_time_interval']['tstart']['orbit_num']
        start_utc_mjd_2000  = bct_vis['xv_time_interval']['tstart']['utc_time']
        start_sec           = bct_vis['xv_time_interval']['tstart']['sec']
        end_orbit           = bct_vis['xv_time_interval']['tstop']['orbit_num']
        end_utc_mjd_2000    = bct_vis['xv_time_interval']['tstop']['utc_time']
        end_sec             = bct_vis['xv_time_interval']['tstop']['sec']
        duration            = end_sec - start_sec
        debug               = False
        processing_in       = start_utc_mjd_2000
        start_ascii_time    = xl_time_processing_to_ascii(proc_id_in,
                                              time_ref_in,
                                              processing_in,
                                              ascii_id_out,
                                              time_ref_out,
                                              debug)
        # Nodal period in seconds
        nodal_period        = 5890.945
        
        if start_sec > nodal_period:
            logger.error(f'T_ANX {start_sec} cannot be higher than the nodal period {nodal_period}')

        direction = None

        if start_sec <= (nodal_period / 4) or start_sec > ((nodal_period / 2) + (nodal_period / 4)):
            direction = "Ascending"
        else:
            direction = "Descending"

        date_format         = '%Y-%m-%dT%H:%M:%S'
        datetime_bct_start  = None

        try:
            datetime_bct_start      = datetime.strptime(start_ascii_time, date_format)
        except Exception as e:
            logger.error(f'Error parsing input datetimes: {e}')
            exit(1)

        if swath['id'] != 'SRM':
            logger.info(f'BCT opportunity => {start_ascii_time} / orbit {start_orbit} / {swath['id']} / {direction}')
        else:
            if datetime_bct_start <= swath['Start_Time'] + TIME_DELTA_SRM_ENTRY:
                logger.info(f'BCT opportunity => {start_ascii_time} / orbit {start_orbit} / {swath['id']} entry (0.5 days) / {direction}')
            elif datetime_bct_start >= swath['Stop_Time'] - TIME_DELTA_SRM_EXIT:
                logger.info(f'BCT opportunity => {start_ascii_time} / orbit {start_orbit} / {swath['id']} exit (2.5 days) / {direction}')
            else:
                logger.info(f'BCT opportunity => {start_ascii_time} / orbit {start_orbit} / {swath['id']} not forbidden / {direction}')

        if duration != 0.0:
            logger.warning('BCT visibility is made of single point which should have no duration')

    if debug == True:
        logger.info('xv_swath_id_close')
    xv_swath_id_close()

# ===========================================================================================================================================================================

def version():
    return package_version('bcops')

if __name__ == '__main__':
    generate_bct_pass()


exit(0)