#!/usr/bin/env python

'''

'''
import os
import json
from pystac_client import Client


from loguru import logger
logger = logger.patch(lambda record: record.update(name=record["file"].name))

from importlib.metadata import version as package_version

import click
CONTEXT_SETTINGS = {"help_option_names": ['-h', '--help'], "max_content_width" : 220}

@click.command(context_settings=CONTEXT_SETTINGS, no_args_is_help = True)
@click.option('--id', '-i',                                              help = 'product id / e.g. BIO_S3_DGM__1S_20251102T210936_20251102T210956_C_G___M___C___T____F065_01_DHI8LY')
@click.option('--version', '-v',     is_flag = True, default = False,    help = 'It shows the version')
@click.option('--Silent', '-S',      is_flag = True, default = False,    help = 'Avoid logging messages')
@click.option('--Debug', '-D',       is_flag = True, default = False,    help = 'Debug flag for verbose messages')


def query_product(id: str, version: bool, silent: bool, debug: bool):

    """
    \b
    Query MAAP catalogue for product metadata extraction.

    Product catalogue metadata information and hierarchy is returned in JSON format.     
    \b

    """    


    if version == True:
        print(f"{os.path.basename(__file__)} - {package_version('bcops')}")
        exit(0)

    URL_LANDING_PAGE   = 'https://catalog.maap.eo.esa.int/catalogue/'
    api                = Client.open(URL_LANDING_PAGE) 
    if debug == True:
        logger.debug(f'querying products {id}')
    results = api.search(
        method  = "GET",
        ids     = [id]
    )

    items = list(results.items())
    
    if len(items) == 0:
        if debug == True:
            logger.debug(f'No items found between with id {id}')
        exit(1)
    
    if len(items) > 1:
        logger.warning(f'More than one item found with id {id}, total items: {len(items)}')
        logger.warning(f'Displaying first item only')
    
    item = items[0]

    if debug == True:
            logger.debug(f"ID: {item.id}, Type: {item.properties['product:type']}, Datatake: {item.properties['eopf:datatake_id']}, Start: {item.properties['start_datetime']}, End: {item.properties['end_datetime']}")

    print(json.dumps( item.to_dict() ) )



def version():
    return package_version('bcops')

if __name__ == '__main__':
    query_product()


exit(0)