#!/usr/bin/env python

import os
import sys
import importlib
import pathlib
import traceback

from datetime import datetime

try:
    import eocfi
except Exception as e:
    print(f'Error importing eocfi: {e}')
    print(f'Please install eocfi:') 
    print('https://eop-cfi.esa.int/index.php/mission-cfi-software/eocfi-software')
    exit(1)

from eocfi.constants import XL_ASCII_CCSDSA
from eocfi.constants import XL_PROC
from eocfi.constants import XL_TIME_UTC
from eocfi.constants import XV_FILE_STF
from eocfi.constants import XL_MODEL_DEFAULT
from eocfi.constants import XF_HEADER_FORMAT_EOF

from eocfi.api    import version as eocfi_version
from eocfi.api_xo import xo_check_library_version
from eocfi.api_xd import xd_read_zone
from eocfi.api_xd import xd_read_zone_id
from eocfi.api_xl import xl_model_init
from eocfi.api_xl import xl_time_ref_init_file
from eocfi.api_xl import xl_time_ascii_to_processing
from eocfi.api_xl import xl_time_processing_to_ascii
from eocfi.api_xl import xl_time_close
from eocfi.api_xo import xo_orbit_init_file
from eocfi.api_xo import xo_orbit_get_val_time
from eocfi.api_xo import xo_orbit_rel_from_abs
from eocfi.api_xo import xo_orbit_close
from eocfi.api_xo import xo_verbose
from eocfi.api_xv import xv_swath_id_init
from eocfi.api_xv import xv_zonevistime_compute
from eocfi.api_xv import xv_swath_id_close

from eocfi.api_xp import xp_atmos_init
from eocfi.api_xf import xf_tree_create
from eocfi.api_xf import xf_tree_create_root
from eocfi.api_xf import xf_tree_create_header
from eocfi.api_xf import xf_tree_set_fixed_header_items
from eocfi.api_xf import xf_tree_add_child
from eocfi.api_xf import xf_tree_add_next_sibling
from eocfi.api_xf import xf_tree_add_attribute
from eocfi.api_xf import xf_tree_set_string_node_value
from eocfi.api_xf import xf_tree_write
from eocfi.constants import XV_FILE_STF
from eocfi.constants import XP_STD_INIT

from loguru import logger
logger = logger.patch(lambda record: record.update(name=record["file"].name))

from importlib.metadata import version as package_version

import click
CONTEXT_SETTINGS = {"help_option_names": ['-h', '--help'], "max_content_width" : 220}

@click.command(context_settings=CONTEXT_SETTINGS, no_args_is_help = True)
@click.option('--start', '-s',                                           help = 'start datetime in format YYYY-MM-DDThh:mm:ss / 2025-10-22T00:00:00')
@click.option('--end', '-e',                                             help = 'end datetime in format YYYY-MM-DDThh:mm:ss / 2025-10-23T00:00:00')
@click.option('--config', '-c',      is_flag = True, default = False,    help = 'It shows the configuration')
@click.option('--version', '-v',     is_flag = True, default = False,    help = 'It shows the version')
@click.option('--Silent', '-S',      is_flag = True, default = False,    help = 'Avoid logging messages')
@click.option('--Debug', '-D',       is_flag = True, default = False,    help = 'Debug flag for verbose messages')


def generate_bct_pass(start: str, end: str, config: bool, version: bool, silent: bool, debug: bool):

    """
    \b
    Generate BCT passes / opportunies.

    TBW
    \b

    """

    if version == True:
        print(f"{os.path.basename(__file__)} - {package_version('bcops')}")
        print(f'eocfi - {eocfi_version()}')
        xo_check_library_version()
        exit(0)

    dist                = importlib.metadata.distribution('eocfi')
    root_dist_info      = dist._path
    dist_info_dir       = pathlib.Path(dist._path).parent
    package_root_dir    = f'{dist_info_dir}/bcops'

    file_orbsct       = f'{dist_info_dir}/bcops/data/BIO_COPS_MPL_ORBSCT'
    file_orbref       = f'{dist_info_dir}/bcops/data/BIO_OPER_MPL_ORBREF_20251121T000000_20270331T000000_0006.EOF'
    file_swtssp       = f'{dist_info_dir}/bcops/data/BIO_OPER_MPL_SWTREF_20251121T000514_20270330T225538_GNDTRACK_0001.EOF' 
    file_gndbct       = f'{dist_info_dir}/bcops/data/BIO_OPER_MPL_ZON_DB_00000000T000000_99999999T999999_BCT______0001.EOF'
    zone_id           = 'BCT'

    if config == True:
        logger.info(file_orbref)
        logger.info(file_swtssp)
        logger.info(file_orbsct)
        logger.info(file_gndbct)
        zone            = xd_read_zone(file_gndbct, zone_id, debug)
        logger.info(zone)
        exit(0)

    list_input_files = []
    list_input_files.append(os.path.splitext(os.path.basename(file_gndbct))[0])
    list_input_files.append(os.path.splitext(os.path.basename(file_orbref))[0])
    list_input_files.append(os.path.splitext(os.path.basename(file_swtssp))[0])
    list_input_files.append(os.path.splitext(os.path.basename(file_orbsct))[0])

    if start is None or end is None:
        print('Error: start and end datetime parameters are required')
        exit(1)

    str_datemjd2000_start  = start
    str_datemjd2000_end    = end
    date_format            = '%Y-%m-%dT%H:%M:%S'
    datemjd2000_start      = None
    datemjd2000_end        = None
    
    try:
        datemjd2000_start      = datetime.strptime(str_datemjd2000_start, date_format)
        datemjd2000_end        = datetime.strptime(str_datemjd2000_end, date_format)
    except Exception as e:
        print(f'Error parsing input datetimes: {e}')
        exit(1)

    # Variables for time conversion
    ascii_id_out        = XL_ASCII_CCSDSA
    time_ref_in         = XL_TIME_UTC
    proc_id_in          = XL_PROC
    time_ref_out        = XL_TIME_UTC  
    mode                = XL_MODEL_DEFAULT

    if debug == True:
        logger.info(f'xl_time_ascii_to_processing => {str_datemjd2000_start}')

    ascii_id_in         = XL_ASCII_CCSDSA
    time_ref_in         = XL_TIME_UTC
    ascii_in            = str_datemjd2000_start
    proc_id_out         = XL_PROC
    time_ref_out        = XL_TIME_UTC
    processing_out      = None
    
    processing_out = xl_time_ascii_to_processing(
                                        ascii_id_in,
                                        time_ref_in,
                                        ascii_in,
                                        proc_id_out,
                                        time_ref_out,
                                        debug)

    mjd2000_start = processing_out

    if debug == True:
        logger.debug(f'xl_time_ascii_to_processing {str_datemjd2000_start} => {mjd2000_start}')

    ascii_in       = str_datemjd2000_end
    processing_out = xl_time_ascii_to_processing(
                                        ascii_id_in,
                                        time_ref_in,
                                        ascii_in,
                                        proc_id_out,
                                        time_ref_out,
                                        debug)

    mjd2000_end = processing_out

    swath_mode      = XV_FILE_STF
    atmos_init_mode = XP_STD_INIT
    atmos_model     = 0
    atmos_init_file = None

    logger.info('xl_model_init')
    xl_model_init(XL_MODEL_DEFAULT, debug)

    logger.info(f'xl_time_ref_init_file => {file_orbref}')
    xl_time_ref_init_file(file_orbref, debug)

    logger.info(f'xo_orbit_init_file => {file_orbref}')
    xo_orbit_init_file(file_orbref, debug)

    logger.info('xp_atmos_init')
    xp_atmos_init(atmos_init_mode, atmos_model, atmos_init_file, debug)

    logger.info(f'xv_swath_id_init => {file_swtssp}')
    xv_swath_id_init(swath_mode, file_swtssp, debug)
 
    '''
        One single zone 'BCT' is expected
    '''
    logger.info('xd_read_zone_id')
    list_zone_id = xd_read_zone_id(file_gndbct, debug)
    zone_id      = list_zone_id[0]

    xd_read_zone(file_gndbct, zone_id, debug)

    debug = False

    logger.info(f'Processing zone {zone_id}')

    list_zone_vis = []
    logger.info(f'xv_zonevistime_compute => {zone_id}')
    try:
        list_zone_vis = xv_zonevistime_compute(file_gndbct, zone_id, mjd2000_start, mjd2000_end, True)
    except Exception as error:
        logger.error(f"Failed {zone_id}")

    for bct_vis in list_zone_vis:
        start_orbit         = bct_vis['xv_time_interval']['tstart']['orbit_num']
        start_utc_mjd_2000  = bct_vis['xv_time_interval']['tstart']['utc_time']
        start_sec           = bct_vis['xv_time_interval']['tstart']['utc_time']
        end_orbit           = bct_vis['xv_time_interval']['tstop']['orbit_num']
        end_utc_mjd_2000    = bct_vis['xv_time_interval']['tstop']['utc_time']
        end_sec             = bct_vis['xv_time_interval']['tstop']['utc_time']
        duration            = end_sec - start_sec

        if duration != 0.0:
            logger.warning('BCT visibility is made of single point which should have no duration')

        debug               = False
        processing_in       = start_utc_mjd_2000
        start_ascii_time    = xl_time_processing_to_ascii(proc_id_in,
                                              time_ref_in,
                                              processing_in,
                                              ascii_id_out,
                                              time_ref_out,
                                              debug)
        
        logger.debug(f'BCT opportunity => {start_ascii_time} / orbit {start_orbit}')

    logger.info('xv_swath_id_close')
    xv_swath_id_close()

    logger.info('xo_orbit_close')
    xo_orbit_close()

    logger.info('xl_time_close')
    xl_time_close()


        


# ===========================================================================================================================================================================


def create_station_unvailability_file(validity_start: datetime, validity_end: datetime, station_info : map, list_input_files : list, debug = False):
 
    if debug == True:
        logger.debug(f"ENTRY : {sys._getframe().f_code.co_name} - station_id = {station_info['station_id']}")

    station_id                  = station_info['station_id']
    station_descriptor          = station_info['descriptor']
    datetime_now                = datetime.now()
    format_date_time_now        = datetime_now.strftime('%Y-%m-%dT%H:%M:%S')
    debug                       = False

    xml_root_name   = 'Earth_Explorer_File'
    fd_afunav_file = xf_tree_create(debug)
    xf_tree_create_root(fd_afunav_file, xml_root_name, debug)
    xf_tree_create_header(fd_afunav_file, XF_HEADER_FORMAT_EOF, debug)
    
    mission_id                  = 'BIO'
    file_type                   = 'MPL_AFUNAV'
    mission                     = 'BIOMASS'
    file_description            = f'AF Unavailability Notification {station_id} by B-COPS'
    notes                       = f'This file defines an X-band reception unavailability for {station_descriptor}'
    file_class                  = 'OPER'
    file_version                = 1
    file_version_str            = '0001'
    system                      = 'PDGS'
    creator                     = 'BCOPS'
    creator_version             = version()
    creation_date               = f'UTC={format_date_time_now}'
    file_name                   = f'{mission_id}_{file_class}_{file_type}_{validity_start.strftime('%Y%m%dT%H%M%S')}_{validity_end.strftime('%Y%m%dT%H%M%S')}_{file_version_str}.EOF'
    utc_validity_start          = f'UTC={validity_start.strftime('%Y-%m-%dT%H:%M:%S')}'
    utc_validity_end            = f'UTC={validity_end.strftime('%Y-%m-%dT%H:%M:%S')}'

    xf_tree_set_fixed_header_items(fd_afunav_file, os.path.splitext(file_name)[0], file_description, notes, mission, file_class, file_type, validity_start.strftime('UTC=%Y-%m-%dT%H:%M:%S'), validity_end.strftime('UTC=%Y-%m-%dT%H:%M:%S'), file_version, system, creator, creator_version, creation_date, debug)

    '''
       *** Variable header elements are NOT allowed by schemas/bmpf/EO_OPER_MPL_AFUNAV_0100.XSD ***
    
    xf_tree_add_child(fd_afunav_file, '/Earth_Explorer_File/Earth_Explorer_Header/Variable_Header/', 'Station_Identifier', debug)
    xf_tree_set_string_node_value(fd_afunav_file, '.', station_id, '%s')

    xf_tree_add_child(fd_afunav_file, '/Earth_Explorer_File/Earth_Explorer_Header/Variable_Header/', 'Station_Descriptor', debug)
    xf_tree_set_string_node_value(fd_afunav_file, '.', station_info['descriptor'], '%s')

    xf_tree_add_child(fd_afunav_file, '/Earth_Explorer_File/Earth_Explorer_Header/Variable_Header', 'List_of_Input_Files', debug)
    xf_tree_add_attribute(fd_afunav_file, '.', 'count', debug)
    xf_tree_set_string_node_value(fd_afunav_file, '@count', '4', '%s')

    xf_tree_add_child(fd_afunav_file, '/Earth_Explorer_File/Earth_Explorer_Header/Variable_Header/List_of_Input_Files', 'Input_File', debug)
    xf_tree_set_string_node_value(fd_afunav_file, '.', list_input_files[0], '%s')

    xf_tree_add_next_sibling(fd_afunav_file, '.', 'Input_File', debug)
    xf_tree_set_string_node_value(fd_afunav_file, '.', list_input_files[1], '%s')

    xf_tree_add_next_sibling(fd_afunav_file, '.', 'Input_File', debug)
    xf_tree_set_string_node_value(fd_afunav_file, '.', list_input_files[2], '%s')

    xf_tree_add_next_sibling(fd_afunav_file, '.', 'Input_File', debug)
    xf_tree_set_string_node_value(fd_afunav_file, '.', list_input_files[3], '%s')

    '''

    xf_tree_add_child(fd_afunav_file, "/Earth_Explorer_File/", "Data_Block", debug)
    xf_tree_add_attribute(fd_afunav_file, '.', 'type', debug)
    xf_tree_set_string_node_value(fd_afunav_file, '@type', 'xml', '%s')

    xf_tree_add_child(fd_afunav_file, '.', 'Unavailability', debug)
    xf_tree_add_child(fd_afunav_file, '.', 'Station_ID', debug)
    xf_tree_set_string_node_value(fd_afunav_file, '.', station_id[:3], '%s')
    xf_tree_add_next_sibling(fd_afunav_file, '.', 'Start_Time', debug)
    xf_tree_set_string_node_value(fd_afunav_file, '.', utc_validity_start, '%s')
    xf_tree_add_next_sibling(fd_afunav_file, '.', 'Stop_Time', debug)
    xf_tree_set_string_node_value(fd_afunav_file, '.', utc_validity_end, '%s')
    xf_tree_add_next_sibling(fd_afunav_file, '.', 'Comments', debug)
    xf_tree_set_string_node_value(fd_afunav_file, '.', f'Station unavailability {station_descriptor}', '%s')

    xf_tree_write(fd_afunav_file, file_name, debug)

    if debug == True:
        logger.debug(f"EXIT : {sys._getframe().f_code.co_name}")


def version():
    return package_version('bcops')

if __name__ == '__main__':
    generate_bct_pass()


exit(0)