#!/usr/bin/env python

'''

> https://explorer.maap.eo.esa.int/

'''

import os
import json
from pystac_client import Client


from loguru import logger
logger = logger.patch(lambda record: record.update(name=record["file"].name))

from importlib.metadata import version as package_version

import click
CONTEXT_SETTINGS = {"help_option_names": ['-h', '--help'], "max_content_width" : 220}

@click.command(context_settings=CONTEXT_SETTINGS, no_args_is_help = True)
@click.option('--id', '-i',                                              help = 'datatake id / e.g. 47919223')
@click.option('--version', '-v',     is_flag = True, default = False,    help = 'It shows the version')
@click.option('--Silent', '-S',      is_flag = True, default = False,    help = 'Avoid logging messages')
@click.option('--Debug', '-D',       is_flag = True, default = False,    help = 'Debug flag for verbose messages')


def query_datatake_id(id: str, version: bool, silent: bool, debug: bool):

    """
    \b
    Query MAAP catalogue for products corresponding to a specific datatake ID.

    \b

    """    

    if version == True:
        print(f"{os.path.basename(__file__)} - {package_version('bcops')}")
        exit(0)

    URL_LANDING_PAGE    = 'https://catalog.maap.eo.esa.int/catalogue/'
    BIO_COLLECTIONS     = ['BiomassLevel0', 'BiomassLevel1a', 'BiomassLevel1b', 'BiomassLevel1c', 'BiomassLevel0IOC', 'BiomassLevel1aIOC', 'BiomassLevel1bIOC', 'BiomassLevel1cIOC']
    api                 = None

    try:
        api = Client.open(URL_LANDING_PAGE)
    except Exception as e:
        logger.error(f"Error when connecting to {URL_LANDING_PAGE}")
        logger.error(f"{e}")
        exit(1)
    
    if debug == True:
        logger.debug(f'querying collections {BIO_COLLECTIONS}')
        logger.debug(f'querying products with datatake-id {id}')
    
    results = api.search(
            method      = "GET",
            collections = BIO_COLLECTIONS,
            filter      = f"eopf:datatake_id={id}"
        )

    items = []
    try:
        items = list(results.items())
    except Exception as e:
        logger.error(f"Error when querying {id}")
        logger.error(f"{e}")
        exit(1)

    if len(items) == 0:
        if debug == True:
            logger.debug(f'No items found between with id {id}')
        exit(1)
    
    for item in items:
        print(f"{item.id}, {item.properties['product:type']}, Start: {item.properties['start_datetime']}, End: {item.properties['end_datetime']}")


def version():
    return package_version('bcops')

if __name__ == '__main__':
    query_datatake_id()


exit(0)